### ISSUE TITLE
Nightmare js not working for multiple clients at the same time

### ISSUE THREAD

**Issue by geethrsn** [segmentio/nightmare#1012]
[Please see this stackoverflow question](http://stackoverflow.com/questions/42398621/handle-multiple-users-requests-to-multiple-remote-web-forms-using-phantomjs?noredirect=1#comment71969732_42398621)

**Comment by rosshinkley** [comment]
Based on the example you posted, you're trying to re-use the same Nightmare instance across multiple requests.  This won't work as if you have multiple requests come in, the actions for the later requests will be added to the currently executing context.  This is further complicated because you're also `.end()`ing the instance, rendering the Nightmare instance unusable after the initial request.

If you move the Nightmare instantiation into the Express `post` method, you will likely have better luck, but be careful: this method will not scale particularly well.

(I'll cross-post this answer on SO.)

**Comment by geethrsn** [comment]
It works. Thank you.
