### ISSUE TITLE
an error has occurred: Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by iwxfer** [segmentio/nightmare#1037]
I am getting this error, is it possible to get more information where it happens?

**Comment by iwxfer** [comment]
I just discovered I can debug with `set DEBUG=nightmare & node spider.js`, but already don't have enough information to fix the issue. Any ideas?

       nightmare queuing process start +0ms                                                                                        
       nightmare queueing action "goto" for http://www.google.com +10ms                                                            
       nightmare queueing action "type" +23ms                                                                                      
       nightmare queueing action "click" +0ms                                                                                      
       nightmare queueing action "wait" +1ms                                                                                       
       nightmare queueing action "evaluate" +0ms                                                                                   
       nightmare running +1ms                                                                                                      
       nightmare electron child process exited with code 0: success! +5s                                                           
     (node:7912) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Cannot read property 'focus' of null

**Comment by jekku** [comment]
usually happens when you select something that doesn't exist / can't be "focused" on. You also didn't have a catch clause after your then.

Would be much better if you post code instead of just the error. It's trivial. We can help you more if we see some snippets.

**Comment by jekku** [comment]
In your JS console, on this very page, try:

```js
document.querySelector('figure').focus() //throws Uncaught TypeError: Cannot read property 'focus' of null
```

**Comment by iwxfer** [comment]
`type` was calling `focus`, I realized that because I run an example and make it fail on wait, evaluate, click, type and goto. I got the focus error when `type` error was introduced.

**Comment by rosshinkley** [comment]
Two things: One, you might want to execute with `DEBUG=*`.  That will give you more helpful errors.  Two, the problem here is there _won't_ be a "full stack trace".  The function that does the evaluation is created, serialized, and reconstituted in the Electron instance, and as such, is sort-of-kind-of out of band.

That said, there was a conversation sort of on this topic a while back in #646.  Might be worth a read and +1. :)

Closing this issue for now as the issue seems resolved.

**Comment by rip747** [comment]
Is it possible to reopen this ticket and just have nightmare tell us what selector was causing the problem? As mentioned, this error occurs when it is trying to focus on an element that doesn't exists. So if I try doing an insert("input[name='email']", "myemail") but there is no input with the name "email" I will get the error. It would be awesome if the error message could be:

Error: done() invoked with non-Error: Cannot read property 'focus' of '"input[name='email']"'

**Comment by jesobreira** [comment]
I think this message should be reviewed, even because a `.type()` can throw this error and make confusion, since the user asked to "type", and not to "focus". Some can say "yeah but to type you have to focus" but it's still unclear, since one may think the `.type()` method just sets the element value.

**Comment by sunnytambi** [comment]
I solved this using `.wait(selector)` method before calling `.type(selector)`
