### ISSUE TITLE
Navigation error

### ISSUE THREAD

**Issue by dhassaine** [segmentio/nightmare#1070]
On some urls I get the following error:
{
  message: 'navigation error',
  code: -3,
  details: ''
}

Any ideas? Thanks.

**Comment by sean-hill** [comment]
I'm getting similar errors intermittently. Typically when redirecting from a previous url.

**Comment by dhassaine** [comment]
This might help, at least it solved the issue for me:
```
.evaluate(() => { })
    .then(() => someFunction(nightmare))
    .catch(error => {
      return someFunction(nightmare);
    })
    .catch();
```
The trick is to evaluate with an empty function before calling your actual evaluation function. If I retry my main evaluation function (here it is called `someFunction`) on an error this seems to resolve almost all of the issues I've been having. I've no idea why the empty evaluate solves the navigation error.

Hope that helps you.

**Comment by sean-hill** [comment]
@dhassaine thanks for your quick suggestion! I'll give that a shot. What a funny solution 😛

**Comment by sweinertjr** [comment]
@dhassaine The reason your code works is because when the error is caught, you're just forcing it to continue anyways:

`   
.catch(error => {
     return someFunction(nightmare);
})
`

This `navigation error` can be ignored - I'm not sure why it is bubbling up, but I've found that you can continue to issue commands to Nightmare and they will successfully complete even after this error is thrown.

**Comment by couhajjou** [comment]
This solves my problem !

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.

**Comment by blacksagres** [comment]
Is there any update regarding this issue? Even with the empty evaluate I still can't get past the error. I use nightmare to run some end to end tests, and they now fail returning the `navigation error` due to an redirection coming from the authentication layer I implemented. 

Not sure if it's relevant but what happens is that the routes are protected and redirect the user to office 365 login if they aren't authenticated, after the login, they are bounced back to the application. 

About my nightmare structure, I have something like this:
```
 const text = await myPage.evaluate(() => {
     // get element and return stuff
    }).end();
```

myPage is an instance of a class implementing the page object pattern, and builds itself with the nightmare functions.

```
export default class DreamJourney {
  constructor() {
    // // Add this config to nightmare when debugging the tests
    // const debugConfig = {
    //   show: true,
    //   width: 1024,
    //   height: 600,
    //   webPreferences: { devTools: 'right' },
    //   waitTimeout: 100000, // in ms      
    // };
    // this.page= nightmare(debugConfig).goto(envConfig.toolboxUI);

    this.page= nightmare().goto(envConfig.testUrl);
    this.rootUrl = envConfig.toolboxUI;
  }

  evaluate = callback => this.page.evaluate(callback);

```

Would appreciate some help on this. :)

**Comment by TahaBoulehmi** [comment]
> Is there any update regarding this issue? Even with the empty evaluate I still can't get past the error. I use nightmare to run some end to end tests, and they now fail returning the `navigation error` due to an redirection coming from the authentication layer I implemented.
> 
> Not sure if it's relevant but what happens is that the routes are protected and redirect the user to office 365 login if they aren't authenticated, after the login, they are bounced back to the application.
> 
> About my nightmare structure, I have something like this:
> 
> ```
>  const text = await myPage.evaluate(() => {
>      // get element and return stuff
>     }).end();
> ```
> 
> myPage is an instance of a class implementing the page object pattern, and builds itself with the nightmare functions.
> 
> ```
> export default class DreamJourney {
>   constructor() {
>     // // Add this config to nightmare when debugging the tests
>     // const debugConfig = {
>     //   show: true,
>     //   width: 1024,
>     //   height: 600,
>     //   webPreferences: { devTools: 'right' },
>     //   waitTimeout: 100000, // in ms      
>     // };
>     // this.page= nightmare(debugConfig).goto(envConfig.testUrl);
> 
>     this.page= nightmare().goto(envConfig.testUrl);
>     this.rootUrl = envConfig.rootUrl;
>   }
> 
>   evaluate = callback => this.page.evaluate(callback);
> ```
> 
> Would appreciate some help on this. :)

The solution is simple:

1. Whenever the error is caught, just force it to continue anyway.
If you would like to use the screenshot function for example:
```javascript
.catch(function (err) { return nighmare.screenshot().then().catch(); });
```
2. Execute`nighmare.end();` when everything is finished:
```javascript
.catch(function (err) { .... }).finally(() => { return nighmare.end() });
```
This is an example:
https://gist.github.com/TahaBoulehmi/0d27bbdf3eea0ac2c5a4cf7618210d9b
