### ISSUE TITLE
How are you using Nightmare?

### ISSUE THREAD

**Issue by reinpk** [segmentio/nightmare#113]
We're seeing a wide variety of use-cases, would love to hear what you've been using it for, thanks!

**Comment by JonForest** [comment]
I've just started to use Nightmare to write automated browser tests, mainly because the API is a lot nicer to use than Selenium's for node.
I'm not altogether sure of a solution, but I've also run into problems where I'm not getting the data back I expect from the website under test, and have not been able to extract enough information to work out why.  
I need to fiddle with it some more; I'm prepared to persist because it's such a graceful API, but if we're going to get Nightmare.js to excel in this area it needs more complete docs and examples.

**Comment by rclai** [comment]
I've been using it to automate to logging in to vendor sites to grab open order reports and it's been quite nice.

**Comment by reinpk** [comment]
FYI we just released `2.x` which seems to fix a lot of problems by migrating from phantomjs to electron under the hood

**Comment by fundkis** [comment]
We at [fund kis](https://fundkis.com) use it to render high quality pdf documents. we used phantomjs for that but since you switched to electron, we migrated to use nightmare. It also simplified our code. Thanks for that but please keep in mind this rendering usage...

**Comment by techtonik** [comment]
We would like to use Nightmare for migrating our test from DalekJS (which is dead), but it seems that Nightmare is Webkit/Chromium only. Electron doesn't work on older systems and doesn't cover Firefox and other browsers.
