### ISSUE TITLE
Page event `will-navigate` returns empty Event object

### ISSUE THREAD

**Issue by adi518** [segmentio/nightmare#1193]
I can log the returned url, so the event works, but the event argument always returns as empty object so it's not possible to stop navigation by `event.preventDefault()`.

**Comment by TimNZ** [comment]
Can't pass functions between the node and Electron process.

Could think of some Nightmare enhancements to handle this, so provide a detailed example/scenario (code) of how you'd like it to work and I'll have a look at it sometime.

**Comment by adi518** [comment]
Not sure how does that relate to the issue? :)

**Comment by TimNZ** [comment]
You can't call event.preventDefault() because the preventDefault() function can't be passed back to Node, it has to be called in the Electron process, and it has to be called synchronously in the event handler in Electron for the 'will-navigate' event.

So if you want to have conditional logic that determines whether to call event.preventDefault() in response to an event, it needs to be passed as an option to whatever action you are using in the Nightmare command chain and executed in Electron.

Make sense?

**Comment by adi518** [comment]
I guess. It's been some time so I have to recall. Thought I saw `event.preventDefault()` mentioned in the API docs when using the callback of this event.

**Comment by TimNZ** [comment]
Fair enough, I'm just going through old issues as I'm making my own major changes and seeing what else looks like it should be in a first cut.
#1254

**Comment by matthewmueller** [comment]
Looks like this has been cleared up, thanks @TimNZ!
