### ISSUE TITLE
Slow on ubuntu server

### ISSUE THREAD

**Issue by hotrush** [segmentio/nightmare#1219]
Running on ubuntu 14.04 with xvfb, but takes too much time to execute.

```
DEBUG=nightmare node index.js 
  nightmare queuing process start +0ms
  nightmare queueing action "goto" for https://anyurl.com/ +2ms
  nightmare queueing action "evaluate" +1ms
  nightmare running +0ms
  nightmare electron child process exited with code 0: success! +36s
```

36 seconds, when it's about 5-6 on local machine. Any thoughts how to make it faster?
VPS 2 cores / 2 GB

**Comment by pawelsamsel** [comment]
I've got the same problem

**Comment by pawelsamsel** [comment]
If you are checking more than 1 url - you can try reuse nightmare instance - this may save you a few seconds from my observations.

**Comment by matthewmueller** [comment]
Hey folks, this issue is a bit broad because it depends on a ton of factors. I did do a sanity test though. 

To try and minimize variance, I ran ubuntu on my computer on the same network inside a docker container. I followed the instructions and code here: https://github.com/segmentio/nightmare/issues/224#issuecomment-365938300

**ubuntu (with xvfb):**

```js
xvfb: 19.545ms
goto: 3138.992ms
title: 16.113ms
Google
```

**osx (no xvfb)**

```
goto: 1905.360ms
title: 2.430ms
Google
```

In my tests it's definitely slower, but not 6x slower.

Going to close this issue, if you're still running into this, please reopen with some more details like the URL, memory on both machines, geolocation of both machines and we can try to help further.
