### ISSUE TITLE
click and wait() spend a lot of time

### ISSUE THREAD

**Issue by ybak** [segmentio/nightmare#123]
Hi, @reinpk:
    I'm using nightmare do integration tests, but I find out it's really slow to do page navigation, especially when there are muliple "click and wait" combinations. for example, this codes here failed sometimes for timeout reason on my computer.
   By using casperjs, the same logic spend less than 15 seonds.
   Maybe it's the internal nodule:phantmjs's problem.
   Hope you can solve this problem.
   Thanks for your great work!

```javascript

describe('Nightmare', function () {
    this.timeout(60000);

    it('shoud not spend a lot of time', function (done) {
        var nightmare = new Nightmare();
        nightmare.goto('https://github.com')
            .click('a[href="/login"]')
            .wait()
            .visible('div#login', function (visible) {
                visible.should.be.true;
                console.log('before login');
            })
            .type('input[name=login]', 'myUsername')
            .type('input[name=password]', 'myPassword')
            .click('input.button')
            .wait()
            .visible('span.octicon-inbox', function (visible) {
                visible.should.be.true;
                console.log('after login');
            })
            .run(done);
    });
});

```

**Comment by snellingio** [comment]
I'm definitely having the same issues:

```
.click('#loginbutton').wait(500)
```
```
nightmare .click() on #u_0_a +25s
nightmare .wait() for 500ms +25s
```

Very odd.

**Comment by timmyg** [comment]
similar issue as well
```` 
 nightmare .setup() phantom instance created +3s
  nightmare .setup() phantom page created +8ms
  nightmare .goto() url: https://mixpanel.com/login/ +1ms
  nightmare .goto() page loaded: success +34s
  nightmare .wait() for the element input#id_email +505ms
  nightmare .type() bob333@gmail.com into input#id_email +111ms
  nightmare .type() password123 into input#id_password +3ms
````

**Comment by johntitus** [comment]
I was having the same issue with [Horseman](https://github.com/johntitus/node-horseman), so I did some investigating. I believe the cause is either phantomjs-node, or perhaps PhantomJS itself, when more than one page.evaluate is called in the same script.  Both click & wait & type all use phantom's page.evaluate under the hood.

I've opened an [issue](https://github.com/sgentle/phantomjs-node/issues/248) with phantomjs-node, hopefully they can track the actual root cause.

**Comment by johntitus** [comment]
The issue turns out to be related to a node module called `shoe`, which wraps socket.js.  Socketjs has a configurable option called heartbleed_delay that shoe does not let you configure.  The default `heartbleed_delay` is 25000 ms. If you manually edit that to something else, like 200 ms, everything gets sped up.

There is an open pull request against shoe to expose this config option in socketjs, but it doesn't look like shoe is actively maintained.  Here's my comment to the phantomjs-node folks. Not sure what they can do about it, except to fork shoe.

https://github.com/sgentle/phantomjs-node/issues/248#issuecomment-75621671

You can manually edit shoe yourself. Go into `node_modules/phantom/shoe/index.js` and change line 8 to read
```js
var server = sockjs.createServer({
        heartbeat_delay : 200
});
```

**Comment by bchr02** [comment]
I am experiencing the same issues on windows with the slowness.

**Comment by reinpk** [comment]
i've also experienced this, and would love to get a fix in place. will try to look into it this coming weekend.

**Comment by nylen** [comment]
Same root cause as #126.  See https://github.com/segmentio/nightmare/issues/126#issuecomment-94948463 for a workaround you can include in your app.

**Comment by reinpk** [comment]
in v2 #200 we're moving off phantomjs for electron, which has been significantly faster in testing.
