### ISSUE TITLE
How to pass class as an argument  to evaluate - Typescript

### ISSUE THREAD

**Issue by basherr** [segmentio/nightmare#1357]
I've come across problem while `evaluating` a `url` and passing `class` as argument. Got error `Cannot read property 'resolve' of undefined`
```
class DomainDriver {
     static resolve() {
          return true;
     }
}
nightmare
            .goto("https://try.honest.com/cart")
            .evaluate(
                (driver: any) => {
                    driver = driver.resolve();
                    // console.log('driver', driver); any way around to make console work?
                    return {
                        // driver,
                        result: document.getElementById("checkout-header").textContent,
                    };
                },
                 DomainDriver
            )
            .end()
```

**Comment by matthewmueller** [comment]
Hi @basherr, unfortunately `evaluate(expr, [args...])` can only take simple values that are serializable (values that works with `JSON.stringify(...)`), because we're handling the arguments from across processes.

Usually there's a way to simplify it to make it possible, possibly using [inject](https://github.com/segmentio/nightmare#injecttype-file)?
