### ISSUE TITLE
Issues Passing Params into .evaluate

### ISSUE THREAD

**Issue by JimTheMan** [segmentio/nightmare#1385]
​Hi, I'm trying to pass values into my evaluate function, but it always seems to come through as "undefined".
I make a nightmare object, 

`let nightmare = new Nightmare({show: true});`
  

Then I try to pass in a value either in array or not, but both log the values as undefined. Why?

```
  let nightmare = await page
        .evaluate( gg => {
        console.log('evaluating yes', gg);
        return gg;
      }, () => {}, yes)
      .end()
      .catch((error) => {
        console.error(JSON.stringify(error));
      });

    console.log('nightmare ', nightmare);
```

(version putting args in array):

` let nightmare = await page
        .evaluate( gg => {
        console.log('evaluating yes', gg);
        return gg;
      }, () => {}, [yes])`

**Comment by matthewmueller** [comment]
Hi @JimTheMan, it's not possible to pass references (complex objects) into evaluate since the arguments are being sent from the node process to an electron process.

Usually you can work around this by either writing a function inside evaluate or on the outside and using `JSON.stringify` and `JSON.parse` to serialize the data.

**Comment by JimTheMan** [comment]
@matthewmueller thanks! Can you el;aborate on what you mean by "writing a function inside evaluate or on the outside"?
