### ISSUE TITLE
unmet wait(sel) results in silent error?

### ISSUE THREAD

**Issue by rauchg** [segmentio/nightmare#171]
I had a situation like:

```js
.wait('input')
.type('input', 'hi')
```

`input` would never match, but then `type` would eventually be attempted.
Made debugging really hard.

**Comment by rauchg** [comment]
Also, while `wait` should surface an error, so should `type`. Instead, `type` targetting an unknown selector results in:

```
phantom stdout: TypeError: 'null' is not an object (evaluating 'document.querySelector(selector).focus')
phantom stdout:   phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3
  phantomjs://webpage.evaluate():3
```

and the test passing with no `err` after calling `run`

**Comment by sinkingshriek** [comment]
I've had similar errors too (the one you mentioned in the 2nd comment). From my understanding so far, this happens when you have two `phantomjs` instances running at the same time. so if I do :-

```
nightmare
.goto('http://github.com')
.type('input', 'hi')
.run(function(err, nightmare){
if(err) return err;
console.log('done');
});

nightmare
.goto('http://twitter.com')
.type('input', 'bye')
.run(function(err, nightmare){
if(err) return err;
console.log('done');
});
```
then I get the `document.querySelector(selector).focus')` error. I've been thinking of mitigating this problem by running the second instance only when the first one completes but I haven't really tested that yet.

**Comment by rosshinkley** [comment]
@shri3k @rauchg Is this still an issue?

**Comment by rosshinkley** [comment]
Taking a closer look at this: `.wait(selector)` now will time out after some period of time.

@shri3k's example is problematic, at least with the Electron implementation: a single Nightmare instance wraps one Electron instance, meaning in general you should not try to do parallel operations on the same instance.  Those actions will enter into a race condition and (probably) behave poorly.

Due to the age of this issue and lack of response, and that there is a viable solution baked in, I'm going to close this issue.  If you have any more problems, feel free to reopen or file a new issue.
