### ISSUE TITLE
How to use V2 correctly?

### ISSUE THREAD

**Issue by idrakimuhamad** [segmentio/nightmare#221]
Based on the example give,

    var Nightmare = require('nightmare');
    yield Nightmare()
      .goto('http://yahoo.com')
      .type('input[title="Search"]', 'github nightmare')
      .click('.searchsubmit');

jshint telling me `A yield statement shall be within a generator function (with syntax: function*)`. Am I missing something to make this work?

**Comment by matthewmueller** [comment]
You'll need to wrap it in a generator function using a library like [co](http://github.com/tj/co) or [vo](http://github.com/lapwinglabs/vo):

```js
var vo = require('vo')
vo(function * () {

  var Nightmare = require('nightmare');
  yield Nightmare()
    .goto('http://yahoo.com')
    .type('input[title="Search"]', 'github nightmare')
    .click('.searchsubmit');

})(fn)
```

This is the recommended approach because it's extremely easy to follow. Alternatively you can use callbacks:

```js
var Nightmare = require('nightmare');
Nightmare()
  .goto('http://yahoo.com')
  .type('input[title="Search"]', 'github nightmare')
  .click('.searchsubmit')
  .run(function (err) {

  })
```

Or even promises (well, thenables):

```js
var Nightmare = require('nightmare');
Nightmare()
  .goto('http://yahoo.com')
  .type('input[title="Search"]', 'github nightmare')
  .click('.searchsubmit')
  .then(fulfill, reject)
```

Hope this helps!
