### ISSUE TITLE
confused with generators - use within express

### ISSUE THREAD

**Issue by tmaximini** [segmentio/nightmare#287]
I try to use nightmare inside an express app. something like this:

```js
router.get('/', function(req, res, next) {

    var getPrice = function* () {
       console.log('hello');  // <-- never even logged
        return yield Nightmare()
            .goto(MY_URL)
            .evaluate(function () {
                return document.querySelectorAll('.price-total .animated')[0].innerText;
            })
            .run();
    };
    res.status(200).json(getPrice());
});
```

I am new to generators and all my attempts with `evaluate` where not successful. I just wish I could use the old `.evaluate(fn, callback)` way. 

Any help greatly appreciated.

**Comment by LarryBattle** [comment]
The problem is that Express 4 `res.json(obj)` / `JSON.stringify()` only accepts objects and primitives and not generators.
If you look at the source code for `res.json(obj)` you can see that all they do is pass the object to `JSON.stringify()`.
Source code: https://github.com/strongloop/express/blob/2f8ac6726fa20ab5b4a05c112c886752868ac8ce/lib/response.js#L242

A generators is an iternator factory. Broadly speaking, to execute a generator you need to initialize it then call `next()` and check for the value property on the returned object.

Simple example:

    var gen = function *(){
      var i = 0;
      yield i++
      yield i++
      yield i++
    }
    var x = gen()
    do{
      var val = x.next().value
      console.log("Got: ", val)
    }while(val !== undefined)
    console.log("DONE")

Output:

    Got:  0
    Got:  1
    Got:  2
    Got:  undefined
    DONE

Tutorial over generators:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators

So if you update your code you should get something like this.

    router.get('/', function(req, res, next) {
        var getPrice = function* () {
           console.log('hello');  // <-- never even logged
            return yield Nightmare()
                .goto(MY_URL)
                .evaluate(function () {
                    return document.querySelectorAll('.price-total .animated')[0].innerText;
                });
        };
        var price = getPrice().next().value
        res.status(200).json(price);
    });

Lastly, I think you might want to use [cheerio](https://github.com/cheeriojs/cheerio) instead Nightmare for scraping webpages.
Tutorial:
https://scotch.io/tutorials/scraping-the-web-with-node-js

**Comment by tmaximini** [comment]
thanks @LarryBattle - I definitely do not want to use cheerio as I need to fill in forms, click buttons etc. on the remote page before parsing it. I am looking into [SpookyJS](https://github.com/SpookyJS/SpookyJS) as well as into nightmare, but with nightmare I am not able to evaluate s simple value and extract it back into express at this time.
I do understand the purpose of generating values, it just doesn't click with me how to use them for scraping, especially if I have a series of remote tasks with multiple `.evaluate` blocks.

**Comment by jim-thisplace** [comment]
Seconding this. In my case, I think the best bet is to switch back to a version older than 2.x.x for the moment.

**Comment by reinpk** [comment]
you're mixing generators in incorrectly... if express supports generators instead of functions with callbacks it'd be something like this:

* function passed to `router.get` is now a generator
* `yield` the `getPrice` function to get the result before sending it along

```
router.get('/', function* (req, res, next) {
    var getPrice = function* () {
       console.log('hello');  // <-- never even logged
        return yield Nightmare()
            .goto(MY_URL)
            .evaluate(function () {
                return document.querySelectorAll('.price-total .animated')[0].innerText;
            })
            .run();
    };
    var price = yield getPrice();
    res.status(200).json(price);
});
```
