### ISSUE TITLE
Mocha example incorrectly passing

### ISSUE THREAD

**Issue by nicolekanderson** [segmentio/nightmare#304]
I'm running the example from the Readme:

```javascript
var Nightmare = require('nightmare');
var expect = require('chai').expect; // jshint ignore:line

describe('test yahoo search results', function() {
  it('should find the nightmare github link first', function*() {
    var nightmare = Nightmare()
    var breadcrumb = yield nightmare
      .goto('http://yahoo.com')
      .type('input[title="Search"]', 'github nightmare')
      .click('.searchsubmit')
      .wait('.url.breadcrumb')
      .evaluate(function () {
        return document.querySelector('.url.breadcrumb').innerText;
      });
    expect(breadcrumb).to.equal('github.com');
  });
});
```

and when I switch out the URL in the expect statement (to something that should definitely fail, like 'asdf'), the test is still showing as passing. I have mocha, chai, and mocha-generators installed, and I'm using `mocha --harmony` to run the files in my test directory. 

After reading issue #295, I tried installing vo and adding in that wrapping syntax, but it doesn't seem to make any difference.

**Comment by LarryBattle** [comment]
I added your test to the `test/index.js` then ran it and got this error.

	 2) test yahoo search results should find the nightmare github link first:
		 Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

The problem seems to be that the search result page on [yahoo.com](https://search.yahoo.com/search?p=github+nightmare) doesn't have any elements that have a class of `url` and `breadcrumb`. Thus the test should timeout if ran properly.

Maybe the reason why your test are passing is because you installed but didn't initialize the `mocha-generator` module. See this on how. https://github.com/segmentio/nightmare/pull/290

**Comment by nicolekanderson** [comment]
Oh jeez, of course, thanks @LarryBattle. 

I added the `require('mocha-generators').install();` line and the tests are now failing. I've tried to get an example that passes, pulling in updated selectors from the yahoo search, but I'm not able to get anything to work. Are there updated examples using Mocha that pass?

**Comment by miaomi** [comment]
I have the same problem here with OS X 10.11.1 node v4.2.1 mocha 2.3.3. I'm new to node.

**Comment by WMeldon** [comment]
I was getting a mocha timeout error but this seems to work fine:

```js
var Nightmare = require('nightmare')
var expect = require('chai').expect // jshint ignore:line
require('mocha-generators').install()

describe('test yahoo search results', function() {
  this.timeout(5000)
  it('should find the nightmare github link first', function*() {
    var nightmare = Nightmare()
    var link = yield nightmare
      .goto('http://yahoo.com')
      .type('input[title="Search"]', 'github nightmare')
      .click('.searchsubmit')
      .wait('.ac-21th')
      .evaluate(function () {
        return document.getElementsByClassName('ac-21th')[0].href;
      });
    expect(link).to.equal('https://github.com/segmentio/nightmare');
    yield nightmare.end()
  });
});
```

If you change the assertion, you end up with a failing test.  I also added ```nightmare.end()``` to close the window when the tests are finished.

**Comment by rosshinkley** [comment]
@nicolekanderson Did you get this sorted out?  If not, have a look at [Nightmare's test suite](https://github.com/segmentio/nightmare/blob/master/test/index.js).

@miaomi Hm, the errors look like `electron-prebuilt` is either not installed or didn't install properly.  Try wiping `node_modules` and running `npm install` again.

@WMeldon It's best practice to end the Nightmare instance when you're done.  Otherwise, the child process will remain running forever and you will (rightfully) get Mocha timeouts.

**Comment by rosshinkley** [comment]
I'm going to go ahead and close this issue due to age, lack of activity, and that I _think_ it's resolved.  If this is still an issue, feel free to reopen/open a new issue.
