### ISSUE TITLE
Size of this package is a nightmare 

### ISSUE THREAD

**Issue by yeralin** [segmentio/nightmare#324]
If we take a look at nightmarejs package size, you are gonna be surprised (maybe). It is ~100mb. It is all because electron package.

My question is the following, is it possible to change it to phantom headless browser?

**Comment by Zn4rK** [comment]
NightmareJS was based on PhantomJS before. But they've sinced then switched to Electron.

Electron makes it possible to utilize any node package you'd like. For PhantomJS to communicate with Node you'll have to open a really ugly socket and transfer the data that way. To understand this better, take a look at some other [phantomjs-node](https://github.com/sgentle/phantomjs-node#no-really-how-does-it-work) packages:  

The binaries in phantomjs may be smaller, but it uses a very old version of QtWebKit (And as of QT 5.4 it is what the Qt team says "done").

I'm interested in this package mainly *because* it's using Electron (which in turn uses Chromium). Disk space is essentially free these days, and the overhead you're creating by using PhantomJS (memory leaks, processing power, etc) is not worth it to switch back.

There are a few other options out there for you, and the closest you'll get is probably [CaseperJS](http://casperjs.org/).

**Comment by reinpk** [comment]
thanks @Zn4rK, that's 100% correct!

**Comment by yeralin** [comment]
Ok, my problem was that I was using Node-webkit, and this package, so my final program's weight was 200+mb. Can I somehow use Electron instead of Node-webkit using Electron from Nightmarejs?

Meaning that I don't want to download electron package since I have it in nightmarejs node_modules.
