### ISSUE TITLE
'page-log' event is missing

### ISSUE THREAD

**Issue by inversion** [segmentio/nightmare#334]
This event are mentioned in the README but don't seem to be implemented, I'm guessing it (and `page-error`) were removed when switching to Electron?

I'm currently working on capturing `console` messages using nightmare. It seems that the `BrowserWindow.webContents` does not fire any `console-message` events - only `<webview>` does (see https://github.com/atom/electron/blob/9f536f47834e920f1f5a4d2e4ace63d95a437095/atom/browser/api/atom_api_web_contents.cc#L303). 

I'm currently working around it by adding an interceptor to console on the renderer in runner.js to pass console messages back using IPC. I've also got an open question about what the reasoning is for the above code on Electron's Slack. I'd be open to making this into a pull request if it sounds like a reasonable approach.

**Comment by ThibWeb** [comment]
Hey @inversion, I was trying to use the `page-error` event and it took me a while to realise that while documented in the README, it is not yet available in the last published release. I had to install from GitHub in order to use it: `npm install --save nightmare@segmentio/nightmare#e556285`.

Hope that helps.

**Comment by inversion** [comment]
Cheers @ThibWeb
