### ISSUE TITLE
Control Flow/Delay Teardown

### ISSUE THREAD

**Issue by trestletech** [segmentio/nightmare#36]
Hi. Thanks for the neat tool.

I'm trying it out tonight and have hit a roadblock that I can't seem to make it around. I'm looking to add a conditional branch to my pipeline -- i.e. if a certain element is visible on the page, then click it and fill out some form, if that element is not visible then just proceed to whatever else you were going to do.

I can't seem to figure out a way to do this without dropping down to raw JS for that alternate flow in an `evaluate` -- which kind of defeats the whole purpose of using this abstraction. I thought about adding the control flow in the callback used in `run()`, but it seems that the `nightmare` instance returned as the second argument there has already been deconstructed, meaning I can't queue up any further interactions with it.

Are there any examples of this functionality?

**Comment by giggioz** [comment]
+1

**Comment by jfrumar** [comment]
I'm struggling with this issue too - I assumed that the 'nightmare' object that's passed into the callback to 'run' would allow further queuing and running.

it looks like I'll have to re-login and initiate my session for each branch in my flow until another option comes along.

**Comment by petecoop** [comment]
I ran into this problem too and found that nightmare doesn't support my needs, so I'm currently working on an alternative called [Phantasma](https://github.com/petecoop/phantasma) which uses Promises to handle the asynchronous methods, rather than queueing. Which means you can change control flow at any point.

It's not ready yet, when I'm sure it's stable I'll release v1.0 however would be nice to have some early feedback either on the API or by beta testing - everything in the API docs is working so far (however before 1.0 release may change at any point).

https://github.com/petecoop/phantasma

**Comment by jfrumar** [comment]
That looks really compelling Pete! Please let us know when it's ready.

**Comment by petecoop** [comment]
Thanks @jfrumar, will do! I've created a [v1.0 milestone](https://github.com/petecoop/phantasma/milestones/v1.0.0) with the issues I aim to complete before going 1.0

**Comment by petecoop** [comment]
Hey @jfrumar, I've just released v1.0 as I've met my original goals - check it out https://github.com/petecoop/phantasma

Open an issue if you've got any feedback

**Comment by reinpk** [comment]
long awaited... but v2 #200 uses generators and an explicit `.end()` method to improve the flow control.
