### ISSUE TITLE
Add an option to show the dock icon

### ISSUE THREAD

**Issue by cevek** [segmentio/nightmare#377]
```
app.dock.hide()
```

**Comment by matthewmueller** [comment]
Yah it should probably be hidden by default, right now I just want Nightmare to be more stable before hiding it, because if there's errors you can end up with a ton of open electron processes. There's logic in the code right now to hide it, but it's commented out: https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L34-L38

**Comment by jviotti** [comment]
I've sent a PR to uncomment this out: https://github.com/segmentio/nightmare/pull/426

**Comment by matthewmueller** [comment]
The default is now to hide it. This issue will serve as a reminder to add an option to show it.

**Comment by jviotti** [comment]
@matthewmueller I just implemented a `showDock` option: https://github.com/segmentio/nightmare/pull/441

**Comment by jviotti** [comment]
@matthewmueller BTW, is there an existing issue to specifically tackle the open electron processes when an error occurs? I'd love to collaborate on that one.

**Comment by rosshinkley** [comment]
@jviotti #409 is _somewhat_ related, is that what you had in mind?
