### ISSUE TITLE
Nightmare is not worthy to develop apps

### ISSUE THREAD

**Issue by sriducati** [segmentio/nightmare#403]
same issue as https://github.com/segmentio/nightmare/issues/224 no one could possibly fix it... now i am sure someone will close this issue as well saying its duplicate, but where is the solution?Nightmare is totally waste for developers its really nightmare.. it works fine in windows but does not even display error in fedora...

**Comment by shri3k** [comment]
@sriducati you do realize how OSS works, right? People are donating thousands of their hours to provide a solution to something that they think someone might find useful and instead of you putting the same effort like others to fix an issue are instead completely demeaning the project? I get utterly disgusted when I see these reactions.
