### ISSUE TITLE
Add more reliable way to populate a text into an element

### ISSUE THREAD

**Issue by nodaguti** [segmentio/nightmare#414]
I found that `nightmare.type()` does not wait for actually finishing the typing since v2.1.0 (i.e. starting to use `sendInputEvent`), which causing populating a long text into an input element to fail in an certain situation.
I created a sample application to describe this issue:

https://github.com/nodaguti/nightmare-type-issue

In this app, `click('[type=submit]')` is executed before finishing to type a long message, resulting that only a partial message is submitted.

This issue is annoying especially when you test a login page or something like that because you have to put `wait(100)` before every `type()` actions to ensure the entire user ID and password are populated.

`type()` is still useful to trigger keyboard-related events like `keypress` properly, so I suggest adding another action `populate(selector, text)` to enter a text into an element synchronously by executing `element.value = text`.

I also created a pull request to implement `populate` action.

**Comment by matthewmueller** [comment]
Let's track this issue: https://github.com/atom/electron/issues/3930

**Comment by nodaguti** [comment]
Thanks for creating an issue for Electron about this problem!
Indeed the root of this issue lies `sendInputEvent` 's asynchoronous, so it's perfect if it is resolved on Electron side.

**Comment by matthewmueller** [comment]
Okay this is turning into a pretty tricky issue. According to #3930, there's not a good way to track asynchronous events. Right now I'm considering two options but could use some feedback.

1) Send less events. Programmatically set the value, then trigger the last character's events (like you're just finishing typing something)

2) Keep current functionality. I've tested it manually, and I haven't been able to reproduce this issue on smaller bodies of text (yet), so it at least it seems somewhat rare. Add an point in an FAQ on how to either override or add a custom action like populate to nightmare (via `.action()`)

I'm leaning towards 1), but I could use some feedback :-)

**Comment by stephenmathieson** [comment]
>  I haven't been able to reproduce this issue on smaller bodies of text (yet)

i've had intermittent failures typing small chunks of text (email addresses) :/

**Comment by matthewmueller** [comment]
I'll be adding this once there's a version bump in electron: https://github.com/atom/electron/pull/4080

:-)

**Comment by stephenmathieson** [comment]
rad dude =)

**Comment by the-t-in-rtf** [comment]
Glad it's not just me.  Rather than just a +1, I thought I'd share a workaround.

I often experience problems when using `type` back to back, where part of the first field's text is intermittently typed into the second field.  For example:

```
nightmare.type(".username", "username").type(".password", "password");
```

You can easily end up with fun stuff like a username set to `userna` and a password set to `mepassword`.  I found that adding a long enough `wait` call between two `type` calls avoids this for now.

Looking forward to the full fix, thanks in advance for following up.

**Comment by matthewmueller** [comment]
hey guys, sorry for the delay on this, i know this is not in a great state right now.

I tested out `sendInput` and it looks like `sendInput` will not work as I was hoping. it will send `input` events, but not `keydown`, `keyup` and `keypress` events. You can read more about it here: https://github.com/atom/electron/issues/3930#issuecomment-172671004

The goal is to make it as much like pressing keys as we can. Unfortunately, there's no way to send keyboard events serially, so I think the approach I will try next is:

**typing "hi":**

```
focus element
keydown event "h"
keypress event "h"
input event "h"
keyup event "h"
delay 30ms
```

the delay will be used to mimic human typing behavior, but more importantly it should ensure that the events are done in order.

Let me know if you have anything thoughts on this otherwise I plan to fix this over the weekend.

**Comment by matthewmueller** [comment]
this is now in 2.1.5 :-)
