### ISSUE TITLE
swallowing electron errors

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/nightmare#421]
we're currently swallowing errors, making debugging nightmare timeouts incredibly difficult:

**timeout.js**

```js

var ms = require('ms');
var Nightmare = require('./')

var n = new Nightmare;
n.goto('http://yahoo.com').end(function() {
  console.log('=)')
  process.exit(0)
});

setTimeout(function() {
  console.error('timeout')
  process.exit(1)
}, ms('30s'))
```

**output**:

```
$ DEBUG=nightmare* node timeout
  nightmare queueing action "goto" for http://yahoo.com +17ms
  nightmare running +3ms
timeout
```

----

running `dist/electron` directly yields:

```
$ node_modules/electron-prebuilt/dist/electron lib/runner.js 
node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

... any reason we're not sending this to `stderr`, or at least notifying the user that something went wrong?

**Comment by shauvik** [comment]
I'm trying to run electron on GCP and get a similar error:

```
$ node_modules/electron-prebuilt/dist/electron lib/runner.js 
electron: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
```

**Comment by Mr0grog** [comment]
Since this was filed, it looks like Nightmare has gotten a *little* better at surfacing electron errors: https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js#L70

…but that really wouldn’t give nearly as much detail as it could. A user would never see the message above from electron, for example:

```
node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
```

One option would be to just send Electron’s stderr through the parent process’s stderr. Users would see deprecation notices and possibly a number of other bits of noisy output from Electron. There’s probably some good to be had there (in trying this, I noticed Nightmare uses several deprecated APIs), but I can imagine there might be other output that is more noisy than helpful.

Another option might be to buffer up Electron’s stderr and emit it when/if Electron exits with a non-zero exit code. Any thoughts?

**Comment by rosshinkley** [comment]
_Bringing this over from #582._

I had been thinking about was wrapping the Electron instance stdout and possibly stderr up with calls to `debug` (rather than piping them straight through to the parent process stdio).  Then I started thinking about possibly having log levels and _maybe_ introducing something slightly more complex than debug like [winston](https://github.com/winstonjs/winston) or [loglevel](https://www.npmjs.com/package/loglevel).  Thoughts?

**Comment by Mr0grog** [comment]
My very minor 2¢: sending Electron’s stdout/stderr to debug channels like `electron:log/election:error` seems like a great idea and gives people lots of flexibility for getting various output. I’m somewhat skeptical that a new, heavier logging tool needs to come along for the ride, but can definitely see ways that doing so might be helpful. Maybe the main question is: what’s the pain point you’re trying to solve switching logging implementations?

- loglevel is great for when you need something light and simple, especially in the browser. That said, switching to it will sacrifice some nice things Nightmare currently has: automatic coloring, prefixing, and timing in log output, plus automatic filtering of loggers by environment variable. That will all have to be re-coded (if we still want it).

- winston is really heavy-duty, but will probably get you all you need straight away with very little extra work. I think you can also query/re-play logs, which might be useful if, say, Electron logging is suppressed but then Electron crashes and we want to output its logs anyway.

**Comment by rosshinkley** [comment]
> sending Electron’s stdout/stderr to debug channels like electron:log/election:error

Yep.  I'd agree. :)  Frankly, for now, I think we _should_ keep it simple, routing electron's stdout/stderr through DEBUG.

> I’m somewhat skeptical that a new, heavier logging tool needs to come along for the ride, but can definitely see ways that doing so might be helpful.

I am too, and I apologize if I didn't make that clear.  I wanted to float the idea to see what everyone thought.  I was tinkering with the idea more seriously after you (@Mr0grog) submitted #579: With the progress events, it might be helpful to add logging there, but would make running Nightmare with DEBUG _wildly_ verbose.  There are probably other events - like any of the events that are simply forwarded - that could be dropped to a lower log level.  My main goal was to help manage verbosity, but that may very well be a misguided early optimization.

winston was at the tip of my brain, and I had to go look up loglevel from a previous project to remember that.  I was throwing out possibilities, they certainly aren't the only two solutions out there.  I'm willing to entertain alternatives.

**Comment by Mr0grog** [comment]
> running Nightmare with DEBUG wildly verbose. There are probably other events - like any of the events that are simply forwarded - that could be dropped to a lower log level.

Getting off topic from this bug, but *oh, certainly.* I think it’s already a little verbose. One simpler thing to do might be just having more granular logging channels, e.g. browser events, script execution, runner actions, queueing, process management, etc. One could potentially manage just as well by message type as by severity.

**Comment by rosshinkley** [comment]
@Mr0grog Yeah, it's getting a _bit_ into the weeds. :)

> One simpler thing to do might be just having more granular logging channels, e.g. browser events, script execution, runner actions, queueing, process management, etc. One could potentially manage just as well by message type as by severity.

For sure.  It's a little bit more of a hassle to set up DEBUG rules to get exactly what you want, but I'm on board.

To that end... with an eventual PR, would it be helpful to include common(ish) DEBUG setups over at nightmare-examples, especially as the more complicated parts start coming in?
