### ISSUE TITLE
Take a whole page screenshot

### ISSUE THREAD

**Issue by icaromh** [segmentio/nightmare#488]
Does exist any way to do it? Something similar to [Full Page Screen Capture Chrome extension](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl) do.

The only way I though was:

* Get the document height
* go scrolling at the end and taking screenshots
* use some external tool to compose a new image

**Comment by rosshinkley** [comment]
Take a look at #328, specifically [my comment](https://github.com/segmentio/nightmare/issues/328#issuecomment-159311982).  The basic gist is to get the dimensions of the body element (using `scrollHeight`/`scrollWidth`), and then use `Nightmare.viewport` to set the viewport dimensions.  After that, you should be able to take a screenshot of the entire page.

The biggest gotcha is waiting for the internal frame backing store to catch up to your request, outlined in #468 and fixed in #479.  Both are probably worth a read.

**Comment by icaromh** [comment]
Oh! Thanks a lot @rosshinkley  :+1:

**Comment by cheapsteak** [comment]
Should this be revisited since the viewport setting doesn't work on windows?

**Comment by ChenYCL** [comment]
> Take a look at #328, specifically [my comment](https://github.com/segmentio/nightmare/issues/328#issuecomment-159311982). The basic gist is to get the dimensions of the body element (using `scrollHeight`/`scrollWidth`), and then use `Nightmare.viewport` to set the viewport dimensions. After that, you should be able to take a screenshot of the entire page.
> 
> The biggest gotcha is waiting for the internal frame backing store to catch up to your request, outlined in #468 and fixed in #479. Both are probably worth a read.

can  i use electron api win.capturePage to get  rect image?
