### ISSUE TITLE
load/store cookies from/to an external file

### ISSUE THREAD

**Issue by shebinleo** [segmentio/nightmare#50]
I believe phantomjs allows to store cookies to an external file

**Comment by twistedlogicusc** [comment]
Any update on this?

**Comment by herlon214** [comment]
Waiting too =/

**Comment by rosshinkley** [comment]
This issue seems to be fairly old, and I believe was against 1.x.x of Nightmare which was based on Phantom.

For what it's worth, adding cookies should be possible with [`cookies.set()`](https://github.com/segmentio/nightmare#cookiessetname-value) added in 2.0.9.

I'm going to consider this issue resolved.  If it's still an issue, feel free to reopen or file a new issue.
