### ISSUE TITLE
Why "this" is undefined inside Nightmare.action?

### ISSUE THREAD

**Issue by moroshko** [segmentio/nightmare#503]
I'm trying to define a custom action:
```js
import Nightmare from 'nightmare';

Nightmare.action('clickWorktypes', () => {
  this.click('[data-automation=workTypes]').wait(500);
});
```
But, I get:
> TypeError: Cannot read property 'click' of undefined

What am I doing wrong?

**Comment by rosshinkley** [comment]
Offhand, I think fat-arrow (`=>`) notation changes the meaning of `this`.  When actions are run, `this` is supplied using `function.apply()`.  If I'm not mistaken, I think what you're doing there is redefining `this` unintentionally.  I think changing the arrow to a traditional function might fix it.

**Comment by moroshko** [comment]
Thanks @rosshinkley! I should have guessed this.

Now, the error has gone, but the action still doesn't work:
```js
Nightmare.action('clickWorktypes', function() {
  console.log('I am running, but doing nothing :(');
  this.click('[data-automation=workTypes]').wait(500);
});

...

nightmare
  .goto(url)
  .clickWorktypes() // This doesn't work, execution hangs here.
  ...
```

This works fine:
```js
nightmare
  .goto(url)
  .click('[data-automation=workTypes]').wait(500)
```

What am I missing here?

**Comment by rosshinkley** [comment]
I should have taken a closer look at the content of your method.  I saw the arrow and responded off-the-cuff.  Time for a closer inspection!

The function parameter for `.action()` accepts a `done` parameter that must be called.  The [`.action()`](https://github.com/segmentio/nightmare#nightmareactionname-actionnamespace) docs show it in the examples, but don't explicitly say it.  (That should _probably_ be fixed.)

The other thing that jumps out at me: you typically don't want to wrap multiple actions in the way you're doing it because it probably won't do what you expect.  Consider the following:

```js
Nightmare.action('example', function(done){
    this.wait('body').screenshot('someScreenshot.png').wait(1000);
    done();
});

var nightmare = Nightmare();
nightmare.goto('http://example.org')
.example()
.goto('http://yahoo.com')
.then(function(){
    nightmare.end(function(){});
});
```

On the face of it, you'd think the order of operations might look like:

1. goto
2. wait
2. screenshot
3. wait
4. goto
5. then
6. end

... but it won't be.  The `.example()` call will add the calls to `.screenshot()` and `.wait()` to the _end_ of the queue, resulting in a picture of Yahoo's homepage.

This is the kind of activity that [`.use()`](https://github.com/segmentio/nightmare#useplugin) is intended for, I think.  Using my previous example:

```js
var example = function(screenshotName){
    return function(nightmare){
        nightmare.wait('body').screenshot(screenshotName).wait(1000);
    };
};

var nightmare = Nightmare();
nightmare.goto('http://example.com')
.use(example('someScreenshot.png'))
.goto('http://yahoo.com')
.then(function(){
    nightmare.end(function(){});
});
```

... will produce the desired result of a picture of example.org's homepage.

For completeness, if you really want to use `.action()`, I think you _technically_ still can.  You could have the Nightmare instance interrupt the queue with a call to `.then()` inside of the action.  Consider:

```js
Nightmare.action('example', function(done){
    this.wait('body').screenshot('someScreenshot.png').wait(1000).then(done);
});

var nightmare = Nightmare();
nightmare.goto('http://example.org')
.example()
.goto('http://yahoo.com')
.then(function(){
    nightmare.end(function(){});
});
```

... will also produce the desired result of a picture of example.org's homepage.

I don't think this was the intent of `.action()`, though.  I can't think of any immediate problems with this, but it wouldn't surprise me if it had downstream consequences.

**Comment by moroshko** [comment]
Thanks a lot @rosshinkley. That was very insightful!
