### ISSUE TITLE
Access the popup opened by the app

### ISSUE THREAD

**Issue by michalbe** [segmentio/nightmare#510]
#### Question
When I click on a given button in my app it opens a popup window using good ol' `window.open(url)`. Can I somehow access it's content? I don't have an access to the `window` object returned by `window.open` in the app because it's in the closure and rebuilding the architecture to gain this access in tests is IMHO an overengineering.

#### Example
Let's say I'm doing something similar to this:
```javascript
var nightmare = Nightmare({ show: true })

nightmare
  .goto('mysite.url')
  .click('#open-popup')
  .magicallySwitchContextOfTheFollowingMethodsToPopup() // <-- this is what I'm looking for
  .type('#popup-input', 'HWDP') // <- type in popup
  .evaluate(function () {
    // do stuff in the popup here
  })
  .end();
```

Any clues?

**Comment by rosshinkley** [comment]
I had experimented with creating a plugin solution for this using #425 to solve [this StackOverflow question](http://stackoverflow.com/questions/34912579/how-can-i-get-a-screenshot-of-a-popup-window-after-login-with-nightmarejs).  I had shelved the experiment because there are a couple of nasty problems - for starters, you can't arbitrarily reassign the `win` reference for the browser window Nightmare uses.  (Doing so would require _significant_ refactoring.)  Second, since the windows Nightmare uses are ostensibly hidden, the provided solution would have to handle/mock focus internally.  Finally, you will lose the ability to run ordinary Nightmare commands against the newly-created window (again, without significant refactoring).

With those limitations in mind, I humbly submit [the outgrowth of that experiment](https://github.com/rosshinkley/nightmare-window-manager).  It has a flavor of `.evaluate()` so you can still do _most_ of what Nightmare offers.  Feedback welcome.

**Comment by rosshinkley** [comment]
Merging into #593.
