### ISSUE TITLE
Why screenshot's height equals to window's height and not document's height?

### ISSUE THREAD

**Issue by moroshko** [segmentio/nightmare#515]
My screenshots always result in 936px height, despite the fact that I call `.viewport()` with a larger height:
```js
const desiredWidth = 920;
const nightmare = Nightmare({
  show: true,  
  waitTimeout: 5000,
  width: desiredWidth + 15, // scrollbar (is there a better way to count for the scrollbar?)
  height: 500 // Value doesn't matter as we change it in .viewport() below
});

nightmare
  .goto('https://en.wikipedia.org/wiki/Nightmare')
  .wait(3000)
  .evaluate(() => {
    return {
      width: document.body.scrollWidth,
      height: document.body.scrollHeight
    };
  })
  .then(({ width, height }) => {
    console.log({ width, height }); // => { width: 920, height: 4638 }
    nightmare.viewport(width, height).wait(1000);
  })
  .then(() => {
    nightmare.screenshot(path.join(screenshotsDir, `${width}.png`));
    // The resulted screenshot is 920px * 936px
    // Why the height is being ignored?
  })
  ...
```
I noticed that 936px is actually `window.innerHeight`, so I wonder why the screenshot is created based on the window height rather than document height.

What am I missing here?

I'm using version `2.2.0`.

**Comment by moroshko** [comment]
Looks like `{show: true}` is causing the issue.

**Comment by rosshinkley** [comment]
`{show:true}` is the "problem", although it's not a bug.  Since you're forcing it to render to a physical output that is smaller than the viewport you specify, Electron will render to the maximum size it can for that physical output.  Without `{show:true}`, the viewport renders in the framebuffer which is practically infinite.

For completeness, this was first identified as a part of [the second bullet of this comment](https://github.com/segmentio/nightmare/issues/328#issuecomment-159311982) in #328.

**Comment by moroshko** [comment]
Thanks @rosshinkley. Your answers are very helpful!
