### ISSUE TITLE
How get call nightmare in cycle?

### ISSUE THREAD

**Issue by 6pm** [segmentio/nightmare#533]
How best way to get in cecle?
`
function clickBtn(){
    nightmare
        .goto('https://site.com/')
        .type('input[name="test-input"]', 'text')
        .click('.add-test')
}

for(var i= 0; i<5; i++) {
    clickBtn();
}
`

**Comment by rosshinkley** [comment]
This is similar to #522.  Nightmare's calls are asynchronous, but can only run one instruction at a time.  Your example is also queueing operations, but never executing them.

There are a couple of options for getting results in series.

### Use `Array.reduce`

You could prepare several operations in a loop, pushing each promise onto an array and then executing the promises in series using `Array.reduce`.  For example:

```js
var Nightmare = require('nightmare');
var nightmare = Nightmare();
var promises = [];

for(var i=0; i<5; i++){
  promises.push(nightmare.goto('http://example.org').title().then());
}

promises.reduce(function(accumulator, promise){
  return accumulator.then(function(results){
    return promise.then(function(title){
      results.push(title);
      return results;
    });
  })
}, Promise.resolve([]))
.then(function(results){
  nightmare.end(function(){
    console.dir(results);
    console.log('done');
  });
});
```

Note the call to `.then()` in the loop.  Without this, Nightmare will queue the `.goto()` and `.title()` calls 5 times, executing them for the first then in the `.reduce()` series.  This will result in one instance of the title and four undefined array members.

### Use [`vo`](https://github.com/lapwinglabs/vo)
Style-wise, vo might be closer to what you have in mind.  This would let you yield in the loop to get the information you want.  For example:

```js
var Nightmare = require('nightmare'),
  nightmare = Nightmare(),
  vo = require('vo');

var run = function*(){
  var results = [];
  for(var i=0; i<5; i++){
    var result = yield nightmare.goto('http://example.org').title();
    results.push(result);
  }
  return results;
}

vo(run)(function(err, results){
  console.dir(results);
  console.log('done');
});
```

### Use [`co`](https://github.com/tj/co)
`co` is similar to `vo`, but instead of taking a callback, it returns a promise.  For example:

```js
var Nightmare = require('nightmare'),
  nightmare = Nightmare(),
  co = require('co');

var run = function*(){
  var results = [];
  for(var i=0; i<5; i++){
    var result = yield nightmare.goto('http://example.org').title();
    results.push(result);
  }
  return results;
}

co(run).then(function(results){
  console.dir(results);
  console.log('done');
});
```

**Comment by rosshinkley** [comment]
I believe this issue is resolved.  If you have more questions about this topic, feel free to reopen/open a new issue.

**Comment by saalmaan** [comment]
Hi @rosshinkley 

I have followed your above example but my promises array is not firing nightmare.

```
const Nightmare = require('nightmare');
const nightmare = Nightmare({show:true});
const $ = require('jquery')(window);
let nightmarelinks = [];
data.categories.map((category, index) => {
    if(category.category.name === 'OFFERS') {
      nightmarelinks.push(nightmare.goto('http://www.example.co.uk/'+category.category.link).title().then());
    } else {
      $(category.subCategories).each((index, cat) => {
        nightmarelinks.push(nightmare.goto('http://www.example.co.uk/'+cat.link).title().then());
      });
    }
  });
```
console.log(nightmarelinks) //84 Promise {pending;}

```
promises.reduce(function(accumulator, promise){
  return accumulator.then(function(results){
    return promise.then(function(title){
      results.push(title);
      return results;
    });
  })
}, Promise.resolve([]))
.then(function(results){
  nightmare.end(function(){
    console.dir(results);
    console.log('done');
  });
});
```

also I would like to run an evaluate function, do have I have to pass it when I am building promise array? 

Many thanks

**Comment by rmoriz** [comment]
Maybe you can add this to the documentation? 

I guess it's a very common case, e.g. when you screen-scrape something and want to download a lot of documents (like invoices) available from a single page, for example.

**Comment by rosshinkley** [comment]
@rmoriz There is _some_ of that in [`nightmare-examples`](https://github.com/rosshinkley/nightmare-examples).  The Nightmare documentation is lean, to be sure, but much of that is intentional.
