### ISSUE TITLE
when type chinese text don't work

### ISSUE THREAD

**Issue by suhaotian** [segmentio/nightmare#549]
don't work:
```js
var N = require('nightmare')

var n = N({
    show: true
})

n.goto('https://www.baidu.com/')
 .type('#kw', '哈哈哈')
 .click('#su')
 .wait('#content_left')
 .evaluate(function () {
    return document.querySelector('#content_left').textContent
 })
 .end()
 .then(function (result) {
    console.log(result)
 })
```

work:
```js
var N = require('nightmare')

var n = N({
    show: true
})

n.goto('https://www.baidu.com/')
 .type('#kw', 'hhh')
 .click('#su')
 .wait('#content_left')
 .evaluate(function () {
    return document.querySelector('#content_left').textContent
 })
 .end()
 .then(function (result) {
    console.log(result)
 })
```

**Comment by rosshinkley** [comment]
You might want to consider using [.insert()](https://github.com/segmentio/nightmare#insertselector-text) instead.  That sets the value you send directly.

There's a reason why this doesn't work: `.type()` uses [`webContents.sendInputEvent()`](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentssendinputeventevent), which restricts input to [accelerator](https://github.com/electron/electron/blob/master/docs/api/accelerator.md) keys.  I'm almost positive you can send unicode characters with `\u` and `webContents.sendInputEvent()`, but at present, Nightmare doesn't support it.  The string you send is simply split, so sending `\u54C8` would result in typing `\u54C8` instead of `哈`.

I've considered adding accelerator support, but there are cases where accelerators don't work like you might expect, like [sending `Return` or `Enter`](https://github.com/electron/electron/issues/5005).  Would sending unicode-encoded characters be useful to you?

**Comment by suhaotian** [comment]
@rosshinkley  thank you

**Comment by rosshinkley** [comment]
@suhaotian Turns out I was wrong.

Sending `\u54c8` _will_ send the correct character.  So either using `.insert()` or `.type()` with unicode encodings should work.
