### ISSUE TITLE
how to write code to prevent any memory issues.

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [segmentio/nightmare#562]
hey, 

I get constant warning about memory limits - when I edit the code in IPC.js to prevent the warning and set the level to max - my program constantly crashes due to node reaching max memory limit :( 

Is there something specific you need to keep in mind to prevent memory leakage problem.

**Comment by Mr0grog** [comment]
Are you creating a lot of separate instances of the `Nightmare` object? If so, the easiest thing you can do now is just make a few and re-use them. Additionally, version 2.3.1 (released yesterday) has a patch that should significantly reduce memory usage.

Given the notes in #561, I think it’s likely that Nightmare will grow some automatic methods for reducing memory usage, but for now, the best approach is to manage a pool of Nightmare instances yourself so as not to create too many and allocate a lot of memory.

**Comment by JoyKrishnaMondal** [comment]
I do only one 
```
browser = require('nightmare')()
```
and then reuse browser. The only thing I would ask is 
when do you call ? 
```
browser.end()
```
I have a lot of code that looks like this 
```livescript
 browser.goto("google.com")
 browser.evaluate(within)
 browser.run(then (browser) )
```
and then 
```livescript
then = (browser) ->
 browser.goto "yahoo.com"
# ..evaluate 
# .. run ( then2 (browser))
```
or should I just use a for loop ? 

```livescript
for I in ["google.com","yahoo.com"]
 browser.goto(I)
 browser.evaluate(within)
 browser.run(foo)
```

**Comment by Mr0grog** [comment]
> The only thing I would ask is when do you call `end()`?

`end()` totally shuts down the browser, so you should only call it when you’re finished with everything. By itself, that won’t actually do anything—you have to call `run()` or `then()` afterwards, like so:

```js
browser.goto("google.com")
browser.evaluate(within)
browser.end()
browser.run((result) ->
  # do something with the results
)
```

> I have a lot of code that looks like this
> ```coffee
> browser.run(then (browser) )
> ```

Is this actually the code that you’re running and is it working? It looks like you’re passing the *result* of your `then` function to `run()` rather than your `then` function itself, which should trigger an error when nightmare finishes running all your actions.

> or should I just use a for loop?

A plain for loop would not be a good idea, since all of Nightmare’s operations are asynchronous. You might want to read up on this article about loops with Nightmare: https://github.com/rosshinkley/nightmare-examples/blob/master/docs/common-pitfalls/async-operations-loops.md

**Comment by rosshinkley** [comment]
Closing for age and it looks like the outstanding questions have been answered.  If you are still having problems or have additional questions, feel free to open a new issue.
