### ISSUE TITLE
Wrong screenshot size/resolution

### ISSUE THREAD

**Issue by apodgorny** [segmentio/nightmare#596]
Here is my code:

`Nightmare({ show: false })
	.viewport(150, 200)
	.goto('http://www.taoism.net/ttc/complete.htm')
	.wait()
	.screenshot('test.png')
	.end()
	.run(function(err, nightmare) {
		console.log('Done.');
	});`

RESULT:
Screenshot dimensions generated: 300x356
Resolution doubled

EXPECTED:
Screenshot dimensions generated: 150x200
Resolution normal (100% zoom)

Attaching generated screenshot.
![test](https://cloud.githubusercontent.com/assets/2205877/14786437/bbf11d44-0ab3-11e6-8af1-295adb046f67.png)

NOTE: the generated result is not proportionally scaled to expected (separate bug?)

**Comment by rosshinkley** [comment]
For the double size: this has to do with high-resolution display.  Viewport dimensions are in browser pixels, not device pixels (thanks to @Mr0grog for pointing out the difference).  For more information, read  [the bottom of #498](https://github.com/segmentio/nightmare/issues/498#issuecomment-189156529).

For the proportional scaling, I'm not sure.  It might be symptoms of the same quirk.

**Comment by Mr0grog** [comment]
As far as proportions, that’s because `viewport` sets the size of the *window* (debatable about whether that’s correct, but that’s what it does), while the screenshot only captures the actual content viewport, so it loses some pixels from the height for the title bar (and on the edges for the window frame, depending on platform).

**Comment by apodgorny** [comment]
Is there any workaround to this? I want to be able to rely on the size I ask of it.

**Comment by Mr0grog** [comment]
There’s no super-easy way, but, as @rosshinkley noted, I wrote a short description of what you can do to counterract this [at the bottom of #498](https://github.com/segmentio/nightmare/issues/498#issuecomment-210710684). You could use a similar mechanism to [set the window’s content area](http://electron.atom.io/docs/v0.37.7/api/browser-window/#winsetcontentsizewidth-height-animate) instead of using Nightmare’s `viewport()` method.
