### ISSUE TITLE
Getting different results from same code locally and on Travis

### ISSUE THREAD

**Issue by ronichoudhury** [segmentio/nightmare#597]
First things first: Nightmare is awesome :heart:

So, I am attempting to use Nightmare as part of our testing workflow, to verify that some visualization components we're developing don't change significantly with each new pull request, etc. Pretty standard stuff. The trouble is, I am getting different-looking results from the same setup on my local development machine and on Travis. My main question is, what governs how Nightmare/Electron/Chromium actually behave at runtime? Are there options besides those I can control from Node (e.g., extant configuration OS-specific base options for Chromium) that control this runtime behavior?

Here are images of one of my vis components, as rendered on my local machine (top), and on Travis (bottom):
![local](https://cloud.githubusercontent.com/assets/2903332/14790137/f78ce502-0add-11e6-8320-832e197b8e91.png)
***
![travis](https://cloud.githubusercontent.com/assets/2903332/14790145/00e6ffd4-0ade-11e6-9c62-bbcd56a35dc2.png)

Note that, while both images have the correct dimensions, there is a spacing difference between them (the top image stretches off to the left, while the bottom one doesn't). I expected both images to be the same.

Here is the Nightmare code I use to create these images:

````javascript
let n = Nightmare({
  show: false,
  useContentSize: true,
  frame: false,
  webPreferences: {
    partition: 'nopersist'
  }
});
````

Both builds begin from scratch, using NPM to manage node dependencies (in the standard way). It's entirely possible that the difference is coming from some other aspect of my setup, but I wanted to pinpoint Nightmare's possible role in it as well.

Thanks in advance!

**Comment by ronichoudhury** [comment]
A related question (that is really about Electron but that you may know the answer to): how can I tell which version of Chromium is being used by Nightmare, via Electron? I am afraid that my local settings for Chrome on my system are somehow affecting my testing output, and I'd like to figure out how to tell whether or not that's happening as a part of this larger effort.

**Comment by Mr0grog** [comment]
> how can I tell which version of Chromium is being used by Nightmare, via Electron?

If you are on the latest for everything, it’s using Chromium 49.0.2623.75. There’s not an easy way to tell (I just made #599), but you can use a plugin to get the info from the electron process:

```js
Nightmare.action('getVersions', function(_, _, parent, _, _, done) {
  parent.on('getVersions', function() {
    parent.emit('getVersions', {
      electron: process.versions.electron,
      chromium: process.versions.chrome
    });
  });
  done();
}, function(done) {
  this.child.once('getVersions', function(versions) {
    done(null, versions);
  });
  this.child.emit('getVersions');
});

Nightmare().getVersions().then(function(versions) {
  console.log(versions);
  process.exit();
});
```

**Comment by Mr0grog** [comment]
Well, the short and pithy answer is that the display is only as consistent between systems as Chromium is, though that’s probably not very helpful ;)

The difference between the two images above is really surprising if the the windows are the same size in both cases. How is the chart drawn and sized? Could it be a timing issue that’s causing some part of the code to get the size wrong? Maybe something do do with the viewport? (Are there any meta tags that affect viewport layout in your page?) Maybe media queries? (e.g. 1x vs. 2x device-pixel-ratio)

If the layout changes at some point based on the width of the window, timing could easily be a big part of this—since every command has to cross between several different processes, there’s not much control over exactly when your screenshot gets taken vs. any async stuff the web page is doing on its own, for example. It’s not uncommon for timing to be very different on a (usually slow) CI server than on your (usually fast) development machine.

> what governs how Nightmare/Electron/Chromium actually behave at runtime?

Plenty of stuff like the above is different based on the hardware available (especially the displays).

On a lower level, there are potentially a *lot* of things; I think you’d really need to dig into all the various interrelated projects to begin to get a meaningful answer to this. Some are set at compile time, too. There is a lot of conditional code in Chromium and Electron that branches based on whether you are building for OS X, X Windows, or Windows. Those things are generally intended to make the results as much the same as possible, though.

As a side note, in your config:

```js
let n = Nightmare({
  show: false,
  useContentSize: true,
  frame: false,
```

`useContentSize` doesn’t have any affect when `frame` is `false`. It also only does anything if `width` and `height` are present (it only works at window creation time; it doesn’t affect sizing calls afterward).

**Comment by ronichoudhury** [comment]
- Thanks for the tip about extracting the version number from Nightmare; that will be helpful for me going forward
- It turns out it was part of the software stack we use to generate those images. They have a "strict autosizing" feature that attempts to balance the main data display size against the axes and other decorations that go in the margins. For some reason that method works very differently on the different platforms, which is where the real mystery lies (rather than in Nightmare/Electron/Chromium configuration). If I instead direct that chart to be rendered with static sizing, then almost all of the rendering differences disappear (there is still a 1-pixel discrepancy in the placement of some labels, but I suspect that's either from the SVG engine or some other quirk of the software we're using).
- Thanks also for the info on `useContentSize`. One question: you said it only does something if `width` and `height` are present - does that not count the default values of `800` and `600` that those parameters get if not specified?

**Comment by Mr0grog** [comment]
> you said it only does something if width and height are present - does that not count the default values of 800 and 600 that those parameters get if not specified?

Oh, you're probably right, I'll bet it does. I'd have to go back and look, at Electron’s code, but don't have a computer handy.

At any rate, having `frame: false` effectively does the same thing, so `useContentSize` is redundant. IIRC, the electron code is something like:

```cpp
if (!hasFrame() || use_content_size_) {
  setSizeForContent(width, height);
}
```

**Comment by ronichoudhury** [comment]
Ah I see. Thanks for the clarification. I should probably dump that flag and specify `width` and `height` for good measure in my code in any case.

And seriously, thanks for the lightning fast responses on my questions!
