### ISSUE TITLE
Screenshot doesn't clip at the bottom of long pages

### ISSUE THREAD

**Issue by apodgorny** [segmentio/nightmare#616]
I am trying to make a screenshot at the bottom of the long page (e.g. http://www.taoism.net/ttc/complete.htm) like so:

    oNightmare
        .viewport(1024, 30000)
        .goto('http://www.taoism.net/ttc/complete.htm')
        .wait()
        .screenshot(sImagePath, {
            x      : 0,
            y      : 27711,
            width  : 1024,
            height : 133
        });

Screenshot file size is 0 bytes. Tested with different `y` parameters, it works until ~8000px.
Expected: screenshot clip works with any `y` value.

Tried using `.scrollTo`, it did not help.

**Comment by rosshinkley** [comment]
After playing around with this and recreating the behavior, it looks like the [resource provider](https://code.google.com/p/chromium/codesearch#chromium/src/cc/resources/resource_provider.cc&sq=package:chromium&type=cs&l=458&rcl=1464366759) deep in the guts of Chromium uses the device limit (I think it's 8 or 16k in general).  This is important because that defines the maximum size of the rendering canvas, which defines the maximum size of the screenshot.  Anything larger and the texture management/WebGL parts start throwing exceptions.

Anything larger, unfortunately I think you'd have to start stitching parts together yourself.
