### ISSUE TITLE
better error

### ISSUE THREAD

**Issue by rickmed** [segmentio/nightmare#633]
Right know it logs something like "Cannot read property 'blur' of null" when there is a not existing selector, would be great for next version to have additional info of the action and what triggered the error, etc :)

Also, if there is a fatal error like a not existing selector, shouldn't the error be logged even if there is no catch?

**Comment by Mr0grog** [comment]
> Also, if there is a fatal error like a not existing selector, shouldn't the error be logged even if there is no catch?

This part is a little debatable (I’m totally with you on better messages)—the reason promises don’t natively do this is because you can always add a rejection handler via `then` or `catch` later after the error occurs. Instead, you can listen for [the `process` object’s `unhandledRejection` event](https://nodejs.org/dist/latest-v4.x/docs/api/process.html#process_event_unhandledrejection):

```js
process.on('unhandledRejection', (error, promise) => {
    console.error("An action failed because:", error);
});
```

**Comment by rosshinkley** [comment]
> Right know it logs something like "Cannot read property 'blur' of null" when there is a not existing selector, would be great for next version to have additional info of the action and what triggered the error, etc :)

This part, however, dovetails with some of the other issues we've been talking about in #645, #646, and #593.  I'm on board for making events have more helpful errors.

**Comment by rosshinkley** [comment]
I'm going to merge this with #646.
