### ISSUE TITLE
Error executing Object.keys within a function in a wait or evaluate call.

### ISSUE THREAD

**Issue by atomless** [segmentio/nightmare#636]
```Javascript
import Nightmare from 'nightmare';

const browser = new Nightmare({
  doc: true, // option to show the electron app icon in the os x doc
  show: true, // show the browser
  openDevTools: true, // open browser dev tools
  waitTimeout: 10000,
  switches: {
    'ignore-certificate-errors': true
  }
}).viewport(1624, 1020).on('console', function(type, message, errorStack){
  console[type]('    - ' + type + ' - ' + message, errorStack || '');
});

let response = browser.goto('http://google.com').evaluate(function() {
  try {
    console.log('expected_state_obj keys:', Object.keys({ data_url : 'http://foo.bar' }));
  } catch(error) {
    console.log(`ERROR! ${error.message} / ${error.stack}`);
  }
});
```
throws this error stack:
```Bash
    - log - ERROR! _keys2 is not defined / ReferenceError: _keys2 is not defined
    at <anonymous>:6:61
    at javascript (<anonymous>:10:15)
    at <anonymous>:15:3
    at EventEmitter.electron.ipcRenderer.on (.../node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/renderer/init.js:44:29)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7) 
  ✖ PAGE LOADED IN BROWSER : https://doc.soa
```

**Comment by Mr0grog** [comment]
Are you using Babel or some other source transformer on this code? (guessing so because you are using `import`). Most likely, the source transformer is changing the `Object.keys()` call to call some other library function, which is then not available in the actual browser window where it gets evaluated.

Have you tried this example code on its own without source transformations?

**Comment by Mr0grog** [comment]
Also, what versions of Node, Nightmare, and Electron are you using?

**Comment by atomless** [comment]
Hi @Mr0grog - well, that's a good thought, but the thing is I can run `Object.keys(...)` without error from everywhere in my test scripts with no error at all. I only get the error when it's run from within a function in a `wait()` or `evaluate()` call.

**Comment by Mr0grog** [comment]
> I only get the error when it's run from within a function in a wait() or evaluate() call.

That adds more evidence for the conclusion, then! The functions you pass to `wait` and `evaluate` don’t run in the current environment—they get transformed back to source code, sent to the browser (an entirely different process, so you can’t share function objects with it), then turned back into functions and executed there. If you have code in those functions that depends on something in your environment (such as a custom implementation of `Object.keys`), they’ll break, because they don’t actually run in your environment.

**Comment by atomless** [comment]
@Mr0grog yep - you must be right. I find it quite surprising that Ava's babel transpiler would mess with Object.keys though!

**Comment by Mr0grog** [comment]
One workaround if you are stuck with that transpiler would be:

```js
let response = browser.goto('http://google.com').evaluate(Function('', `
  console.log('expected_state_obj keys:', Object.keys({ data_url : 'http://foo.bar' }));
`));
```

**Comment by rosshinkley** [comment]
Looks like this issue is resolved, so I'm going to go ahead and close it.  If this is still a problem, feel free to reopen/submit a new issue.
