### ISSUE TITLE
serializing error output

### ISSUE THREAD

**Issue by rosshinkley** [segmentio/nightmare#646]

**Comment by Mr0grog** [comment]
> (From #645) Once we've got consistent error reporting between the parent and child process, the errors over IPC almost falls out of that for free. Entirely possible I'm missing something, though.

So, quick example of what I was getting at:

```js
// runner.js
parent.respondTo('goto', function(url, headers, done) {
  if (typeof url !== 'string') {
    throw new TypeError('goto: `url` must be a non-empty string');
  }
```

Results in an error object back in the user’s process of `{}`—not super helpful! Right now we return strings or generic objects for errors (when we bother to return errors :P), which is not as nice. And if there is an actual exception in Nightmare’s code (as opposed to Nightmare explicitly returning error information), we have the same situation. That said, returning *something* in all the explicit error cases is waaaaaaaay more important. The serialization thing is more of a nicety (but not a free one).

**Comment by rosshinkley** [comment]
> That said, returning something in all the explicit error cases is waaaaaaaay more important. The serialization thing is more of a nicety (but not a free one).

I should have chosen words more carefully.  Freeish?  Cheap?  Close to free?  Free enough?  Free as in mattress?  Take your pick.  My point was you could manage the explicit error data cases internally to the IPC to mimic real capital-E Errors easily enough, so long as the data is consistent.

Anyway, explicit errors are much more important, you're right about that.

**Comment by Mr0grog** [comment]
VIOLENT AGREEMENT! Anyway, back to the main topic here: figuring out the current state of affairs:

**goto**
- Error: a string for bad arguments (ideally, this should be a `TypeError`)
- Error: an object when the operation fails
- Return: an object with data about the HTTP response

**engineVersions**
- Cannot error
- Return: Object with data

**title**
- Should not ever error
- Return: string

**url**
- Should not ever error
- Return: string

**visible**
- Should not ever error
- Return: boolean

**exists**
- Should not ever error
- Return: boolean

**click, mousedown, mouseover, type, insert, check, uncheck, select**
- Error: may get a string error message, but not one that clearly indicates what went wrong (selector not found). See also #651
- Return: nothing

**forward**
- Should not ever error (open question: _should_ it error if there’s nothing to go forward _to?_)
- Return: nothing

**back**
- Should not ever error (open question: _should_ it error if there’s nothing to go back _to?_)
- Return: nothing

**refresh**
- Should not ever error
- Return: nothing

**wait**
- Error: actual `Error` instance on timeout
- Return: nothing if too few args (but does debug log the situation)
- Return: nothing if argument is an unknown type (does *not* debug log the situation)
- Return: nothing on success

**evaluate**
- Error: actual `Error` instance for invalid arguments (ideally should be `TypeError`)
- Error: string for errors in the evaluated function
- Return: return value of evaluated function (when JSON-serializable)

**inject**
- Error: throws unhandleable async error for errors reading the file
- Return: nothing

**viewport**
- Appears to be incapable of erroring, but may behave oddly or hang if args are incorrect
- Return: nothing (could be value here in returning the actual resulting size, which may differ from requested size)

**useragent**
- Should not ever error
- Return: nothing

**scrollTo**
- Error: throws unhandleable async error if too few args (`TypeError: done is not a function`)
- No error, but potentially odd behavior if wrong argument types
- Return: nothing (like viewport, maybe useful to return the resulting scroll position)

**screenshot**
- Error: actual `Error` instance for file writing issues (permissions, paths, etc)
- Error: throws unhandleable async error if clip rect doesn’t have the required properties or is not an object
- Return: buffer if no path specified, nothing if path is specified

**html**
- Error: empty object if invalid value for `saveType` (it’s an error in Electron, but gets quashed by IPC serialization)
- Return: nothing

**pdf**
- Error: throws unhandleable async error if only one argument and it is not a string or object or if first argument of two is truthy but not a string
- Error: throws unhandleable async error if PDF generation actually fails (using, for example, an invalid `options` object like `{printBackground: 5}`)
- Return: buffer if no path specified, nothing if path is specified

**authentication**
- Should not be capable of erroring directly
- **Hangs indefinitely if given incorrect credentials**
- Error: throws unhandleable async error if called more than once (`Error: callback can only be called for once`)
- Return: nothing

**cookies.get, cookies.set, cookies.clear**
- May have odd errors if too many args
- Errors because of incorrect values get quashed into an empty object
- Return: single cookie object or array of cookie objects for get, nothing for set and clear

**run**
- Error: asynchronous, unhandleable runtime error if a callback function is not provided (See #500)

**then**
- Should never error
- Return: promise

**Comment by avimar** [comment]
AH, the error from evaluate is a string.

That's why `error.message` wasn't working.

OK
