### ISSUE TITLE
Error when running the example code

### ISSUE THREAD

**Issue by Nisthar** [segmentio/nightmare#669]
I am trying to run the example code:
```
var Nightmare = require('nightmare');
new Nightmare({show : true})  
  .goto('http://yahoo.com')
    .type('input[title="Search"]', 'github nightmare')
    .click('.searchsubmit')
    .run(function (err, nightmare) {
      if (err) return console.log(err);
      console.log('Done!');
    });
```
Its returning an error `Cannot read property 'blur' of null` in the console. 
Any solutions?

**Comment by rosshinkley** [comment]
In versions prior to 2.5.0, this (cryptic) error generally meant that one of your selectors was not finding the specified element.  I think Yahoo runs some form of A/B or has different page characteristics based on the requester.  This problem has cropped up before (#116, #490, and I think there were some others).  The Readme version of the example was patched in 2.4.0, the [runnable example](https://github.com/segmentio/nightmare/blob/2.5.0/example.js) in 2.5.0.

My first suggestion would be to update your example to the 2.5.0 version and try running it again.

**Comment by Nisthar** [comment]
Thanks. I had encountered it in my code too when there is no selector
found.

**Comment by BerlinaLI** [comment]
I am running the example code on c9,io, a virtual machine for ubuntu. 
The example.js does not return anything. Could someone review what the problem here?
I am a total beginner for node.js and c9 so the issue might lie in some very simple process. 
![qq 20161129141240](https://cloud.githubusercontent.com/assets/8443821/20698718/f11e9c40-b63d-11e6-96ad-dcbb443af18f.jpg)
![qq 20161129141223](https://cloud.githubusercontent.com/assets/8443821/20698717/f11de214-b63d-11e6-8b9a-5c378f664144.jpg)
![qq 20161129141152](https://cloud.githubusercontent.com/assets/8443821/20698719/f1236202-b63d-11e6-82fd-ea032d08df4d.jpg)

**Comment by rosshinkley** [comment]
@BerlinaLI I have a suspicion you might be hitting #224.  Thoughts?
