### ISSUE TITLE
.pdf doesn't seem to be working on Ubuntu 16

### ISSUE THREAD

**Issue by bradleygore** [segmentio/nightmare#706]
Hey - this project is awesome!

I am, however, having a bit of trouble with the .pdf functionality. I have set breakpoints in the callback for the internal pdf action function, and it does return an error - however that error is just a blank object - nothing in it. I've been trying multiple options and such to try to get this to work, or to at lest return an actionable error, but come up empty... Would really appreciate any input/advise you may have :smile: 

```
var tmpFileName = path.join(__dirname, reportId + '.pdf'),
    pdfOpts = {
        marginsType: 2, //minimum
        pageSize: 'letter',
        landscape: false
};

function renderReport(reportData, reportId) {
    return Nightmare(nightmareOpts)
        .goto(reportData.url + '&format=pdf', {
            'Authorization': 'Bearer ' + superSecretToken
        })
        // internal action - it works fine and has been tested  
        .forcePrintMedia()
        .wait(function() {
            //Client app sets this to true when data has been
            //  processed and report fully generated
            return window.isReadyToRumble;
        })
        .screenshot(tmpFileName.replace('.pdf', '.png')) // this works perfectly!
        //.pdf(tmpFileName, pdfOpts) // --> this gives a sad :(
        .end()
        .then(function() {
            //this is what gets passed to consumer in .then function
            return fs.createReadStream(tmpFileName.replace('.pdf', '.png'));
        });
}
```

**Comment by rosshinkley** [comment]
Two problems afoot here.  

Let's address the immediate problem first: why it's crashing.  You have specified a `pageSize` of `letter`, which [according to the Electron docs](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentsprinttopdfoptions-callback) should be capital-L `Letter`.  The page size is (evidently) case-sensitive as `letter` crashes on my Ubuntu 16.04 image and `Letter` works fine.

Onto the other problem: why the output was empty.  `.pdf()` tries to happily pass the error argument up the IPC chain, and since `Error` does not have helpful enumerable properties, the information is omitted. This falls under the banner of what #646 was trying to accomplish.

**Comment by bradleygore** [comment]
@rosshinkley Oh man - I totally overlooked the casing being off... that solved it - so sorry to have bugged you for that. Thanks a ton for your excellent help!!!
