### ISSUE TITLE
Best way to window.onload?

### ISSUE THREAD

**Issue by stevenvachon** [segmentio/nightmare#769]
I need to wait for "DOMContentLoaded" + images, so I need the full "load" event. Having difficulty finding a way to make it work.

These didn't work:
```js
.wait(() => document.readyState==="complete")
```
```js
.wait(function(){ return document.readyState==="complete" })
```

**Comment by stevenvachon** [comment]
Hmm, it turns out that my issue was not with a "load" event, but with `documentElement.offsetHeight` calculations. Doing `wait(50)` fixes it -- so it's just an old browser issue.

My original question stills stands though. This needs to be documented somewhere at least, so it might as well be here.

**Comment by rosshinkley** [comment]
Nightmare, by default, will wait for the [`did-stop-loading`](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-did-stop-loading) event.  This event is typically emitted once the page is "finished" loading (be it from the original 20x completing or `stop` being called).  At that point, the page should already be in a ready state.  (Should.  If it isn't, or you have a a countercase, I'd love to hear about it.)

However, `complete` may not be helpful: you could still have client-side scripts issuing requests for assets to load asynchronously, or already-loaded assets modifying the DOM in flight.  I'm not _entirely_ sure what your use case is, though, and I suspect there may be more to it than I think.

**Comment by stevenvachon** [comment]
Thanks!

**Comment by cwhenderson20** [comment]
I'm actually having a similar issue. I have found that using the above `wait` function _does_ work, but not consistently on a headless linux setup.

The reason I am not simply relying on nightmare's idea of when the page is finished loading is that in my testing, the `did-stop-loading` event is fired once there is a significant (but small) amount of time after any assets (scripts, css, iframes) referenced on the page have finished loading. The event is then fired again after those assets have loaded, but by that point, nightmare has already moved on and (in my case) taken a screenshot of a mostly blank page. 

I am loading pages that tend to have a large number of iframes, all of which typically load in external assets as well. Maybe this could be the problem (as I haven't seen too many issues regarding premature promise resolutions)?

Strangely, running the same service that's responsible for loading the pages and using nightmare to take screenshots locally on my Mac almost _never_ (if ever) has a problem using the above `wait` function in order to determine when the page is actually finished loading.

I understand that nightmare most likely does not much of a recourse in terms of listening to events fired from the underlying electron instance, but I haven't delved into the code too deeply, so if it is possible to fix that way, then great!

If anyone has an alternative way to help nightmare make a best guess as to when the page has loaded, I'm all ears!

**Comment by bchr02** [comment]
Check out my solution here: https://github.com/segmentio/nightmare/issues/830#issuecomment-256383157

**Comment by bchr02** [comment]
@rosshinkley In regards to your comment https://github.com/segmentio/nightmare/issues/769#issuecomment-244780554:
>Nightmare, by default, will wait for the did-stop-loading event. This event is typically emitted once the page is "finished" loading (be it from the original 20x completing or stop being called). At that point, the page should already be in a ready state. (Should. If it isn't, or you have a a countercase, I'd love to hear about it.)

I have opened https://github.com/segmentio/nightmare/issues/854 which provides a test case showing that there in fact is an issue with nightmare not finishing loading before moving on to the next chained method.
