### ISSUE TITLE
Cannot type(selector, 0)

### ISSUE THREAD

**Issue by yoz** [segmentio/nightmare#777]
Because 0 is falsy, type() and insert() evaluate the `text || '' == ''` case instead of actually typing the value. Hence `type(selector, 0)` clears the selector.

The workaround is to `type(selector, '0')`.

**Comment by rosshinkley** [comment]
This is (I'd think) expected behavior.  The documentation could probably be a little clearer, stating that `.type()` and `.insert()` _should_ take strings, but don't necessarily have to (eg, `.type('#someInput', true)` types the string "true" the selected element).  Both functions do their best with what they are given.  To that end, I don't think it's a particularly great idea to enforce only strings.  (I'm open to counterargument, though.)

That said, the documentation _is_ pretty clear about what happens with falsey values, which as you note, `0` is an example.
