### ISSUE TITLE
chained methods keep firing before page finishes loading

### ISSUE THREAD

**Issue by bchr02** [segmentio/nightmare#854]
In the below test case we load yahoo.com, fill in the search box with the word "test", click the search button and finally run some code within an ```.evaluate()``` to extract the page title. One would expect the page title to be "test - Yahoo Search Results" instead of the previous page's title of "Yahoo". However that is not the case, Apparently after a ```.click()``` nightmare does not wait for the page to load before allowing the subsequent chained methods to continue.

test case:
```javascript
var Nightmare = require('nightmare');
var nightmare = Nightmare({
    show: true
});

nightmare
    .goto('http://yahoo.com')
    .insert("#uh-search-box", "test")
    .click("#uh-search-button")
    .evaluate(function() {
        return document.title;
    })
    .end()
    .then(function(title) {
        console.log(title);
    })
    .catch(function(error) {
        console.error(error);
    });
```

**Comment by Mr0grog** [comment]
Well, this is kinda tough… Nightmare *does* wait for pages to finish loading before executing each action. However, there’s a gap of 30ms or so (on my machine) between clicking the button and actually starting a navigation. Yahoo stops the default form submission on click and does it themselves, asynchronously, with JavaScript, so I’m guessing that’s the cause of the delay.

That means there’s actually time for Nightmare to run a command before the browser ever gets told to submit the form and load a new page. After the `click` action, Nightmare checks to see whether a new page is loading and, since it is not (yet), continues on with the `evaluate` action.

Short of inserting an automatic delay between every action (or maybe just after input actions, like `click` and `insert`?), I’m not sure there’s really anything that can be reasonably done here. The existing behavior does work (or at least used to) with native form submission. The issue is that Yahoo’s form submission is actually delayed.

**Comment by bchr02** [comment]
@Mr0grog Thank you for researching this. I think I found another solution, please check it out:

```javascript
var Nightmare = require('nightmare');

Nightmare.action('waitforunload', function (done) {
    this.evaluate_now(function() {
        return new Promise(function(resolve, reject) {
            window.onbeforeunload = function() {
                resolve();
            };
        });
    }, done)
});

var nightmare = Nightmare({
    show: true
});

nightmare
    .goto('http://yahoo.com')
    .insert("#uh-search-box", "test")
    .click("#uh-search-button")
    .waitforunload()
    .evaluate(function() {
        return document.title;
    })
    .end()
    .then(function(title) {
        console.log(title);
    })
    .catch(function(error) {
        console.error(error);
    });
```

Basically, when you know you need to wait for the page to unload before moving on you would place ```.waitforunload()``` and nightmare will not move on until it is resolved. I think I should submit a pull request to add this feature natively. Please let me know your thoughts.

**Comment by bchr02** [comment]
One issue with this solution is that if the page never unloads the waitTimeout is not respected. I need to see how I can get around this.

**Comment by bchr02** [comment]
Okay, so returning the promise within an evaluate seems to work better because it still respects the timeout. I wonder if this is a bug with ```Nightmare.action```? Anyways, here is the revised code that works properly:

```javascript
var Nightmare = require('nightmare');

var nightmare = Nightmare({
    waitTimeout: 5000,
    show: true
});

var waitforunload = function() {   
    return new Promise(function(resolve, reject) {
        window.onbeforeunload = function() {
            resolve();
        };
    });
};

nightmare
    .goto('http://yahoo.com')
    .insert("#uh-search-box", "test")
    .click("#uh-search-button")
    .evaluate(waitforunload)
    .evaluate(function() {
        return document.title;
    })
    .end()
    .then(function(title) {
        console.log(title);
    })
    .catch(function(error) {
        console.error(error);
    });
```

**Comment by Mr0grog** [comment]
> `.evaluate()` seems to work better because it still respects the executionTimeout (instead of the nightmare queue getting stuck). I wonder if this is a bug with `Nightmare.action`?

It’s a little unclear (especially given its name), but `executionTimeout` is specifically a timeout for the `evaluate` *action* (not for anything else, and therefore not for `evaluate_now`). It definitely reads like it’s a generic timeout for all actions (and it might be good if there was one!), but it’s not. The behavior your getting is by design, whether or not it’s a *good* design :P

So! That just means you have to implement the timeout yourself:

```js
Nightmare.action('waitForUnload', function (done) {
    var maxWaitTime = this.options.executionTimeout; // or whatever you like
    this.evaluate_now(function() {
        return new Promise(function(resolve, reject) {
            window.onbeforeunload = function() {
                resolve();
            };
        });
    }, done);
    // It's OK not to clean up this timer; once `done` has been called,
    // later calls to it are ignored.
    setTimeout(function() {
      done({message: 'waitForUnload timeout'});
    }, maxWaitTime);
});
```

It’s a little more complicated, but if you want to avoid setting an event listener inside the page, you can also:

```js
Nightmare.action(
  'waitForNavigation',
  function (name, options, parent, window, renderer, done) {
    parent.respondTo('waitForNavigation', function (timeout, done) {
      function startedNavigation () { done(); }
      
      if (window.webContents.isLoadingMainFrame()) {
        return startedNavigation();
      }
      window.webContents.once('will-navigate', startedNavigation);
      
      setTimeout(function () {
        window.webContents.removeListener('will-navigate', startedNavigation);
        done({
          message: `waitForNavigation timed out after ${timeout}ms`
        });
      }, timeout);
    });
    done();
  },
  function(done) {
    var maxWaitTime = this.options.executionTimeout; // or whatever you like
    this.child.call('waitForNavigation', maxWaitTime, done);
  });
```

**Comment by bchr02** [comment]
@Mr0grog Thank for the extra option but did you see my other solution  here https://github.com/segmentio/nightmare/issues/854#issuecomment-256658926 which uses an ```.evaluate()``` instead of an action? I seem to like this the best because it's the cleanest and clearest solution, in my opinion.

**Comment by Mr0grog** [comment]
I did! I find the evaluate solution a little less clean and clear, personally ;)

**Comment by Mr0grog** [comment]
(Which is not to say that it’s bad! It’s just as valid and solves the problem well.)

**Comment by bchr02** [comment]
@Mr0grog it would be awesome if your non-event listener option within https://github.com/Mr0grog could be added directly to nightmare. Care to send a pull request. 😄
