### ISSUE TITLE
Nightmare runs only successful on first run

### ISSUE THREAD

**Issue by DennisKo** [segmentio/nightmare#891]
I am using this code:

```
nightmare
    .goto(URL)
    .wait('.some-selector')
    .evaluate(function () {
        data = {}
        data.title = document.querySelector('.my-selector').innerText
        return data;
    })
    .end()
    .then(function (result) {
     // do some logic
    })
   .catch(function (error) {
     console.error('Search failed:', error);
  });     
```  

It is working on every 1st run after I start the node process. Every subsequent run silently "fails".

1st run:
nightmare queueing action "goto" for URL +8s
  nightmare queueing action "wait" +0ms
  nightmare queueing action "evaluate" +2ms
  nightmare running +1ms
  nightmare electron child process exited with code 0: success! +4s
SUCCESS! It is doing the logic part!

2nd run:
  nightmare queueing action "goto" for URL +8s
  nightmare queueing action "wait" +1ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +1ms

Nothing happens after that. No errors. With show:true no window pops up. Every subsequent run is the same behaviour.

**Comment by saginadir** [comment]
After nightmare is finished running and you reached the .end() you have to create a new nightmare instance.

I had the exact same issue several days ago and I solved it by writing a small class which returns a new nightmare instance every time.

```
import initNightmare from 'nightmare';

// Some options I set for all instances
const nightmareOptions = {
  gotoTimeout: 10000,
  loadTimeout: 15000,
};

class Nightmare {
  static getNewNightmare() {
    return initNightmare(nightmareOptions);
  }
}

export default Nightmare;
```

and then you simply call
`let nightmare = Nightmare.getnewNightmare()`

remember to set the nightmare as null after you finished working with it to prevent memory leaks if your process runs for long.

```
let nightmare = Nightmare.getnewNightmare();

nightmare
  .goto(...)
// do stuff
  .end(() => { nightmare = null })
```

Last word of warning. If you run the .evaluate function the .end() function must remain empty due to a bug which I am about to submit. In that case You'll have to figure a different way to nullify the nightmare.

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to re-open if its still an issue.
