### ISSUE TITLE
Passing a callback function to .end(someFunc) together with .evaluate freezes nightmare 

### ISSUE THREAD

**Issue by saginadir** [segmentio/nightmare#899]
Here's an example:

Working ( notice the .end() call )
```
nightmare
      .goto('http://yahoo.com')
      .wait(1000)
      .evaluate(() => 42)
      .end()
      .then((result) => {
        console.log(result); // Prints 42
      })
      .catch((error) => {
        console.error('Search failed:', error);
      });
```

NOT WORKING and freezing without doing anything
```
nightmare
      .goto('http://yahoo.com')
      .wait(1000)
      .evaluate(() => 42)
      .end(() => { console.log('code finished running'); })
      .then((result) => {
        console.log(result); // Statement never reached :(
      })
      .catch((error) => {
        console.error('Search failed:', error);
      });
```

I assume because some Promise is not chained properly, I have no idea why this is happening.

**Comment by rosshinkley** [comment]
The `.end(fn)` method calls run, which kicks off the queue.  The subsequent `.then()` is also trying to kick off the queue, but because it was cleared by the prior call to `.end(fn)`, Nightmare will immediately halt execution, causing the instance to effectively be hung.

Curiously, there's no unit tests around handling `.end()` with a callback.

I'll be fixing both problems (at least as a first pass) shortly.

**Comment by entrptaher** [comment]
This issue is distantly related to this issue here https://github.com/segmentio/nightmare/issues/660
