### ISSUE TITLE
A way to toggle show during a script?

### ISSUE THREAD

**Issue by yourfavorite** [segmentio/nightmare#907]
I'd like a way to have Nightmare run headless and if a certain event happens, display the browser window. I've looked through the docs and some of the source code but can't seem to find a way. I know there is screenshot functionality, but I'd like to have the ability to interact with things. Thanks!

**Comment by wiliame** [comment]
@yourfavorite nightmare uses electron BrowserWindow:

https://github.com/electron/electron/blob/master/docs/api/browser-window.md

There are 2 functions:

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winshow
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winhide

```
win.show()
Shows and gives focus to the window.

win.showInactive()
Shows the window but doesn't focus on it.

win.hide()
Hides the window.
```

So, if you want to call them, you can extend nightmare:

```
Nightmare.action('show',
    function(name, options, parent, win, renderer, done) {
        parent.respondTo('show', function(inactive, done) {
            if(inactive) {
                win.showInactive();
            } else {
                win.show();
            }

            done();
        });

        done();
    },
    function(inactive, done) {
        this.child.call('show', inactive, done);
    });

Nightmare.action('hide',
    function(name, options, parent, win, renderer, done) {
        parent.respondTo('hide', function(done) {
            win.hide();
            done();
        });

        done();
    },
    function(done) {
        this.child.call('hide', done);
    });
```

And then:

```
var start = +Date.now();
var options = {
    show: true,
};

var client = new Nightmare(options);

client
    .goto('http://google.com/')
    .wait(1000)
    .hide()
    .goto('http://facebook.com/')
    .wait(1000)
    .show()
    .end()
    .then(() => {
        console.info("Loaded in " + (+Date.now() - start));
    });
```

There is something wrong, because after the last `.show`, the `end` is ignored. I will fix it later, for now you can start with this.

**Comment by yourfavorite** [comment]
This is great! Thanks @wiliame

**Comment by meeple142** [comment]
Thank you!
