### ISSUE TITLE
How do I make nightmare click on this?

### ISSUE THREAD

**Issue by pfftdammitchris** [segmentio/nightmare#942]
I am trying to click an individual href element that are exactly the same as others (there are 4 total of these. Here is the element:

    <a href="#" ng-if="d.AvailableStatus != 'UNKNOWN'" ng-click="openDialog2('popuptempl1','/ImportAvailability/GetContainerInfoByContainerNumber',{Container_Nbr:d.WLContainerNumber, Terminal_Cd:d.TerminalCode},'Container Details')" class="ng-binding ng-scope">TCLUZZZZ004</a>

The problem is I do not know how to select one. None of them have a unique ID. They all share the same class names. Only the href text is unique which is 'TCLUZZZZ004' 

Thank you.

**Comment by jekku** [comment]
Use .evaluate().

**Comment by urlysses** [comment]
If you know that the href text is unique and always remains the same, you can use [CSS3 attribute selectors](https://www.w3.org/TR/css3-selectors/#attribute-selectors) to reach the element.

For example: `click("a[href*='TCLUZZZZ004']")`.

The code above uses `*=` to match any `a` tag whose `href` contains the substring "TCLUZZZZ004".

**Comment by jekku** [comment]
I don't know why @urlysses deleted his answer, but using the css selector is a way better option than my initial answer

**Comment by pfftdammitchris** [comment]
I tried using evaluate() but I dont know how to get it to return the value to my click() line. Or do I use click() inside the evaluate function before it gets returned?

**Comment by jekku** [comment]
like @urlysses said, you can use css3 styled selectors.
```js
nightmare.click([href=TCLUZZZZ004]);
```

not sure why he deleted his answer.

**Comment by rosshinkley** [comment]
@jekku - @urlysses' answer would only work if the HREF attribute contained the text in question, not the text element under the anchor.  In other words, the answer - while useful - didn't address the question.

From here, @pfftdammitchris, I think you have two options off the top of my head.  One: you could use `.evaluate()` and try to issue clicks directly.  Something like:

```js
nightmare.goto('http://www.example.org')
  .evaluate(()=>{
    var elements = Array.from(document.querySelectorAll('a')).filter(a=>/information/.test(a.innerText))
    //you'll probably want to do some validation here
    elements[0].click();
  })
  .end()
  .then()
```

This clicks directly on the first element that matches text in the anchor's text, in this case, `information`.  This approach doesn't _always_ work, it depends on the JS framework you're using - in your case it looks like Angular, so your mileage may vary.

Option two: add a class to the anchor you want to click, then use the existing `.click()` machinery to issue your click.  This may work better in your situation, especially if you decide you'd rather use something like [`nightmare-real-mouse`](https://www.npmjs.com/package/nightmare-real-mouse) instead of the internal click events to Nightmare:

```js
nightmare.goto('http://www.example.org')
  .evaluate(()=>{
    var elements = Array.from(document.querySelectorAll('a')).filter(a=>/information/.test(a.innerText))
    //you'll probably want to do some validation here
    elements[0].className += " my-click-class";
  })
  .click('.my-click-class')
  .end()
  .then()
```

**Comment by pfftdammitchris** [comment]
^ Those demonstrations were really helpful. If the website i'm scraping from is using the jquery library, am I able to select elements using jquery syntax? $("#fdfsdf").html()   etc

**Comment by jekku** [comment]
@pfftdammitchris yes. As long as you are sure that JQuery is always loaded. You can even use all the other functions of JQuery to perform interactions / manipulations within an evaluate call.

**Comment by urlysses** [comment]
Sorry! Deleted my answer because I re-read the question and saw that I misunderstood the initial question. I should instead have edited with a more appropriate answer or update. Thanks @jekku and @rosshinkley.

**Comment by stefanspirkl** [comment]
@rosshinkley The example is really helpful and works fine with a-tags. Would it also be possible to click on a div?

My approach:


```
if (elementExists) {
console.log('start inner loop')
return nightmare
.click('form[action*="removed"] [id=removed]')
.wait(2500)
// click the confirm link
evaluate(()=>{
    var elements = Array.from(document.querySelectorAll('div')).filter(div=>/Confirm/.test(div.innerText))
    console.log(elements)
    elements[0].click();
})
.wait(1500)
}
```

The code based on your snippet does not throw an exception, but doesn't click the Div and does not log something. Is there something I am doing wrong?
